// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pingpong.proto

package org.wildfly.camel.test.grpc.subA;

public final class PingPongProto {
  private PingPongProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_apache_camel_component_grpc_test_PingRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_apache_camel_component_grpc_test_PingRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_apache_camel_component_grpc_test_PongResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_apache_camel_component_grpc_test_PongResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016pingpong.proto\022$org.apache.camel.compo" +
      "nent.grpc.test\"1\n\013PingRequest\022\021\n\tping_na" +
      "me\030\001 \001(\t\022\017\n\007ping_id\030\002 \001(\005\"2\n\014PongRespons" +
      "e\022\021\n\tpong_name\030\001 \001(\t\022\017\n\007pong_id\030\002 \001(\0052\372\003" +
      "\n\010PingPong\022w\n\014PingSyncSync\0221.org.apache." +
      "camel.component.grpc.test.PingRequest\0322." +
      "org.wildfly.camel.test.grpc.subA.test.Pon" +
      "gResponse\"\000\022z\n\rPingSyncAsync\0221.org.apach" +
      "e.camel.component.grpc.test.PingRequest\032" +
      "2.org.wildfly.camel.test.grpc.subA.test.P",
      "ongResponse\"\0000\001\022z\n\rPingAsyncSync\0221.org.a" +
      "pache.camel.component.grpc.test.PingRequ" +
      "est\0322.org.wildfly.camel.test.grpc.subA.te" +
      "st.PongResponse\"\000(\001\022}\n\016PingAsyncAsync\0221." +
      "org.wildfly.camel.test.grpc.subA.test.Pin" +
      "gRequest\0322.org.apache.camel.component.gr" +
      "pc.test.PongResponse\"\000(\0010\001B2\n\037org.apache" +
      ".camel.component.grpcB\rPingPongProtoP\001b\006" +
      "proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_org_apache_camel_component_grpc_test_PingRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_apache_camel_component_grpc_test_PingRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_apache_camel_component_grpc_test_PingRequest_descriptor,
        new java.lang.String[] { "PingName", "PingId", });
    internal_static_org_apache_camel_component_grpc_test_PongResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_org_apache_camel_component_grpc_test_PongResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_apache_camel_component_grpc_test_PongResponse_descriptor,
        new java.lang.String[] { "PongName", "PongId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
