// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pingpong.proto

package org.wildfly.camel.test.grpc.subA;

public interface PongResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.wildfly.camel.test.grpc.subA.test.PongResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string pong_name = 1;</code>
   */
  java.lang.String getPongName();
  /**
   * <code>string pong_name = 1;</code>
   */
  com.google.protobuf.ByteString
      getPongNameBytes();

  /**
   * <code>int32 pong_id = 2;</code>
   */
  int getPongId();
}
