// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pingpong.proto

package org.wildfly.camel.test.grpc.subA;

public interface PingRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.wildfly.camel.test.grpc.subA.test.PingRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string ping_name = 1;</code>
   */
  java.lang.String getPingName();
  /**
   * <code>string ping_name = 1;</code>
   */
  com.google.protobuf.ByteString
      getPingNameBytes();

  /**
   * <code>int32 ping_id = 2;</code>
   */
  int getPingId();
}
