/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 * Generated on: Fri May 04 15:50:21 CEST 2018
 */
package org.wildfly.camel.test.salesforce.dto;

import javax.annotation.Generated;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Salesforce Enumeration DTO for picklist Rating
 */
@Generated("org.apache.camel.maven.CamelSalesforceMojo")
public enum Account_RatingEnum {

    // Cold
    COLD("Cold"),
    // Hot
    HOT("Hot"),
    // Warm
    WARM("Warm");

    final String value;

    private Account_RatingEnum(String value) {
        this.value = value;
    }

    @JsonValue
    public String value() {
        return this.value;
    }

    @JsonCreator
    public static Account_RatingEnum fromValue(String value) {
        for (Account_RatingEnum e : Account_RatingEnum.values()) {
            if (e.value.equals(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException(value);
    }

}
