/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 */
package org.wildfly.camel.test.salesforce.dto;

import javax.annotation.Generated;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Salesforce Enumeration DTO for picklist StatusCode
 */
@Generated("org.apache.camel.maven.CamelSalesforceMojo")
public enum Contract_StatusCodeEnum {

    // Activated
    ACTIVATED("Activated"),

    // Draft
    DRAFT("Draft"),

    // Expired
    EXPIRED("Expired"),

    // InApproval
    INAPPROVAL("InApproval"),

    // Terminated
    TERMINATED("Terminated");


    final String value;

    private Contract_StatusCodeEnum(String value) {
        this.value = value;
    }

    @JsonValue
    public String value() {
        return this.value;
    }

    @JsonCreator
    public static Contract_StatusCodeEnum fromValue(String value) {
        for (Contract_StatusCodeEnum e : Contract_StatusCodeEnum.values()) {
            if (e.value.equals(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException(value);
    }

}
