/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 */
package org.wildfly.camel.test.salesforce.dto;

import javax.annotation.Generated;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Salesforce Enumeration DTO for picklist CleanStatus
 */
@Generated("org.apache.camel.maven.CamelSalesforceMojo")
public enum Contact_CleanStatusEnum {

    // Acknowledged
    ACKNOWLEDGED("Acknowledged"),

    // Different
    DIFFERENT("Different"),

    // Inactive
    INACTIVE("Inactive"),

    // Matched
    MATCHED("Matched"),

    // NotFound
    NOTFOUND("NotFound"),

    // Pending
    PENDING("Pending"),

    // SelectMatch
    SELECTMATCH("SelectMatch"),

    // Skipped
    SKIPPED("Skipped");


    final String value;

    private Contact_CleanStatusEnum(String value) {
        this.value = value;
    }

    @JsonValue
    public String value() {
        return this.value;
    }

    @JsonCreator
    public static Contact_CleanStatusEnum fromValue(String value) {
        for (Contact_CleanStatusEnum e : Contact_CleanStatusEnum.values()) {
            if (e.value.equals(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException(value);
    }

}
