/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 */
package org.wildfly.camel.test.salesforce.dto;

import javax.annotation.Generated;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Salesforce Enumeration DTO for picklist Type
 */
@Generated("org.apache.camel.maven.CamelSalesforceMojo")
public enum Opportunity_TypeEnum {

    // Existing Customer - Downgrade
    EXISTING_CUSTOMER___DOWNGRADE("Existing Customer - Downgrade"),

    // Existing Customer - Replacement
    EXISTING_CUSTOMER___REPLACEMENT("Existing Customer - Replacement"),

    // Existing Customer - Upgrade
    EXISTING_CUSTOMER___UPGRADE("Existing Customer - Upgrade"),

    // New Customer
    NEW_CUSTOMER("New Customer");


    final String value;

    private Opportunity_TypeEnum(String value) {
        this.value = value;
    }

    @JsonValue
    public String value() {
        return this.value;
    }

    @JsonCreator
    public static Opportunity_TypeEnum fromValue(String value) {
        for (Opportunity_TypeEnum e : Opportunity_TypeEnum.values()) {
            if (e.value.equals(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException(value);
    }

}
