/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 */
package org.wildfly.camel.test.salesforce.dto;

import javax.annotation.Generated;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Salesforce Enumeration DTO for picklist DeliveryInstallationStatus__c
 */
@Generated("org.apache.camel.maven.CamelSalesforceMojo")
public enum Opportunity_DeliveryInstallationStatusEnum {

    // Completed
    COMPLETED("Completed"),

    // In progress
    IN_PROGRESS("In progress"),

    // Yet to begin
    YET_TO_BEGIN("Yet to begin");


    final String value;

    private Opportunity_DeliveryInstallationStatusEnum(String value) {
        this.value = value;
    }

    @JsonValue
    public String value() {
        return this.value;
    }

    @JsonCreator
    public static Opportunity_DeliveryInstallationStatusEnum fromValue(String value) {
        for (Opportunity_DeliveryInstallationStatusEnum e : Opportunity_DeliveryInstallationStatusEnum.values()) {
            if (e.value.equals(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException(value);
    }

}
