/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 * Generated on: Fri May 04 15:50:21 CEST 2018
 */
package org.wildfly.camel.test.salesforce.dto;

import javax.annotation.Generated;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Salesforce Enumeration DTO for picklist StatusCode
 */
@Generated("org.apache.camel.maven.CamelSalesforceMojo")
public enum Order_StatusCodeEnum {

    // A
    A("A"),
    // C
    C("C"),
    // D
    D("D"),
    // E
    E("E");

    final String value;

    private Order_StatusCodeEnum(String value) {
        this.value = value;
    }

    @JsonValue
    public String value() {
        return this.value;
    }

    @JsonCreator
    public static Order_StatusCodeEnum fromValue(String value) {
        for (Order_StatusCodeEnum e : Order_StatusCodeEnum.values()) {
            if (e.value.equals(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException(value);
    }

}
