/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 * Generated on: Fri May 04 15:50:21 CEST 2018
 */
package org.wildfly.camel.test.salesforce.dto;

import javax.annotation.Generated;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Salesforce Enumeration DTO for picklist Type
 */
@Generated("org.apache.camel.maven.CamelSalesforceMojo")
public enum Order_TypeEnum {

    ; // empty picklist!

    final String value;

    private Order_TypeEnum(String value) {
        this.value = value;
    }

    @JsonValue
    public String value() {
        return this.value;
    }

    @JsonCreator
    public static Order_TypeEnum fromValue(String value) {
        for (Order_TypeEnum e : Order_TypeEnum.values()) {
            if (e.value.equals(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException(value);
    }

}
