/*
 * Salesforce Query DTO generated by camel-salesforce-maven-plugin
 */
package org.wildfly.camel.test.salesforce.dto;

import com.thoughtworks.xstream.annotations.XStreamImplicit;
import org.apache.camel.component.salesforce.api.dto.AbstractQueryRecordsBase;

import java.util.List;
import javax.annotation.Generated;

/**
 * Salesforce QueryRecords DTO for type Contract
 */
@Generated("org.apache.camel.maven.CamelSalesforceMojo")
public class QueryRecordsContract extends AbstractQueryRecordsBase {

    @XStreamImplicit
    private List<Contract> records;

    public List<Contract> getRecords() {
        return records;
    }

    public void setRecords(List<Contract> records) {
        this.records = records;
    }
}
