/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 */
package org.wildfly.camel.test.salesforce.dto;

import javax.annotation.Generated;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Salesforce Enumeration DTO for picklist DigestFrequency
 */
@Generated("org.apache.camel.maven.CamelSalesforceMojo")
public enum User_DigestFrequencyEnum {

    // D
    D("D"),

    // N
    N("N"),

    // W
    W("W");


    final String value;

    private User_DigestFrequencyEnum(String value) {
        this.value = value;
    }

    @JsonValue
    public String value() {
        return this.value;
    }

    @JsonCreator
    public static User_DigestFrequencyEnum fromValue(String value) {
        for (User_DigestFrequencyEnum e : User_DigestFrequencyEnum.values()) {
            if (e.value.equals(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException(value);
    }

}
