/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin.
 */
package org.wildfly.camel.test.salesforce.dto;

import java.util.ArrayList;
import java.util.List;

import javax.annotation.Generated;

import com.thoughtworks.xstream.annotations.XStreamAlias;
import com.thoughtworks.xstream.annotations.XStreamConverter;

import org.apache.camel.component.salesforce.api.PicklistEnumConverter;
import org.apache.camel.component.salesforce.api.dto.AbstractDescribedSObjectBase;
import org.apache.camel.component.salesforce.api.dto.Attributes;
import org.apache.camel.component.salesforce.api.dto.ChildRelationShip;
import org.apache.camel.component.salesforce.api.dto.InfoUrls;
import org.apache.camel.component.salesforce.api.dto.NamedLayoutInfo;
import org.apache.camel.component.salesforce.api.dto.RecordTypeInfo;
import org.apache.camel.component.salesforce.api.dto.SObjectDescription;
import org.apache.camel.component.salesforce.api.dto.SObjectDescriptionUrls;
import org.apache.camel.component.salesforce.api.dto.SObjectField;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Salesforce DTO for SObject User
 */
@Generated("org.apache.camel.maven.CamelSalesforceMojo")
@XStreamAlias("User")
public class User extends AbstractDescribedSObjectBase {

    public User() {
        getAttributes().setType("User");
    }

    private static final SObjectDescription DESCRIPTION = createSObjectDescription();

    private String Username;

    @JsonProperty("Username")
    public String getUsername() {
        return this.Username;
    }

    @JsonProperty("Username")
    public void setUsername(String Username) {
        this.Username = Username;
    }

    private String LastName;

    @JsonProperty("LastName")
    public String getLastName() {
        return this.LastName;
    }

    @JsonProperty("LastName")
    public void setLastName(String LastName) {
        this.LastName = LastName;
    }

    private String FirstName;

    @JsonProperty("FirstName")
    public String getFirstName() {
        return this.FirstName;
    }

    @JsonProperty("FirstName")
    public void setFirstName(String FirstName) {
        this.FirstName = FirstName;
    }

    private String CompanyName;

    @JsonProperty("CompanyName")
    public String getCompanyName() {
        return this.CompanyName;
    }

    @JsonProperty("CompanyName")
    public void setCompanyName(String CompanyName) {
        this.CompanyName = CompanyName;
    }

    private String Division;

    @JsonProperty("Division")
    public String getDivision() {
        return this.Division;
    }

    @JsonProperty("Division")
    public void setDivision(String Division) {
        this.Division = Division;
    }

    private String Department;

    @JsonProperty("Department")
    public String getDepartment() {
        return this.Department;
    }

    @JsonProperty("Department")
    public void setDepartment(String Department) {
        this.Department = Department;
    }

    private String Title;

    @JsonProperty("Title")
    public String getTitle() {
        return this.Title;
    }

    @JsonProperty("Title")
    public void setTitle(String Title) {
        this.Title = Title;
    }

    private String Street;

    @JsonProperty("Street")
    public String getStreet() {
        return this.Street;
    }

    @JsonProperty("Street")
    public void setStreet(String Street) {
        this.Street = Street;
    }

    private String City;

    @JsonProperty("City")
    public String getCity() {
        return this.City;
    }

    @JsonProperty("City")
    public void setCity(String City) {
        this.City = City;
    }

    private String State;

    @JsonProperty("State")
    public String getState() {
        return this.State;
    }

    @JsonProperty("State")
    public void setState(String State) {
        this.State = State;
    }

    private String PostalCode;

    @JsonProperty("PostalCode")
    public String getPostalCode() {
        return this.PostalCode;
    }

    @JsonProperty("PostalCode")
    public void setPostalCode(String PostalCode) {
        this.PostalCode = PostalCode;
    }

    private String Country;

    @JsonProperty("Country")
    public String getCountry() {
        return this.Country;
    }

    @JsonProperty("Country")
    public void setCountry(String Country) {
        this.Country = Country;
    }

    private Double Latitude;

    @JsonProperty("Latitude")
    public Double getLatitude() {
        return this.Latitude;
    }

    @JsonProperty("Latitude")
    public void setLatitude(Double Latitude) {
        this.Latitude = Latitude;
    }

    private Double Longitude;

    @JsonProperty("Longitude")
    public Double getLongitude() {
        return this.Longitude;
    }

    @JsonProperty("Longitude")
    public void setLongitude(Double Longitude) {
        this.Longitude = Longitude;
    }

    private org.apache.camel.component.salesforce.api.dto.Address Address;

    @JsonProperty("Address")
    public org.apache.camel.component.salesforce.api.dto.Address getAddress() {
        return this.Address;
    }

    @JsonProperty("Address")
    public void setAddress(org.apache.camel.component.salesforce.api.dto.Address Address) {
        this.Address = Address;
    }

    private String Email;

    @JsonProperty("Email")
    public String getEmail() {
        return this.Email;
    }

    @JsonProperty("Email")
    public void setEmail(String Email) {
        this.Email = Email;
    }

    private Boolean EmailPreferencesAutoBcc;

    @JsonProperty("EmailPreferencesAutoBcc")
    public Boolean getEmailPreferencesAutoBcc() {
        return this.EmailPreferencesAutoBcc;
    }

    @JsonProperty("EmailPreferencesAutoBcc")
    public void setEmailPreferencesAutoBcc(Boolean EmailPreferencesAutoBcc) {
        this.EmailPreferencesAutoBcc = EmailPreferencesAutoBcc;
    }

    private Boolean EmailPreferencesAutoBccStayInTouch;

    @JsonProperty("EmailPreferencesAutoBccStayInTouch")
    public Boolean getEmailPreferencesAutoBccStayInTouch() {
        return this.EmailPreferencesAutoBccStayInTouch;
    }

    @JsonProperty("EmailPreferencesAutoBccStayInTouch")
    public void setEmailPreferencesAutoBccStayInTouch(Boolean EmailPreferencesAutoBccStayInTouch) {
        this.EmailPreferencesAutoBccStayInTouch = EmailPreferencesAutoBccStayInTouch;
    }

    private Boolean EmailPreferencesStayInTouchReminder;

    @JsonProperty("EmailPreferencesStayInTouchReminder")
    public Boolean getEmailPreferencesStayInTouchReminder() {
        return this.EmailPreferencesStayInTouchReminder;
    }

    @JsonProperty("EmailPreferencesStayInTouchReminder")
    public void setEmailPreferencesStayInTouchReminder(Boolean EmailPreferencesStayInTouchReminder) {
        this.EmailPreferencesStayInTouchReminder = EmailPreferencesStayInTouchReminder;
    }

    private String SenderEmail;

    @JsonProperty("SenderEmail")
    public String getSenderEmail() {
        return this.SenderEmail;
    }

    @JsonProperty("SenderEmail")
    public void setSenderEmail(String SenderEmail) {
        this.SenderEmail = SenderEmail;
    }

    private String SenderName;

    @JsonProperty("SenderName")
    public String getSenderName() {
        return this.SenderName;
    }

    @JsonProperty("SenderName")
    public void setSenderName(String SenderName) {
        this.SenderName = SenderName;
    }

    private String Signature;

    @JsonProperty("Signature")
    public String getSignature() {
        return this.Signature;
    }

    @JsonProperty("Signature")
    public void setSignature(String Signature) {
        this.Signature = Signature;
    }

    private String StayInTouchSubject;

    @JsonProperty("StayInTouchSubject")
    public String getStayInTouchSubject() {
        return this.StayInTouchSubject;
    }

    @JsonProperty("StayInTouchSubject")
    public void setStayInTouchSubject(String StayInTouchSubject) {
        this.StayInTouchSubject = StayInTouchSubject;
    }

    private String StayInTouchSignature;

    @JsonProperty("StayInTouchSignature")
    public String getStayInTouchSignature() {
        return this.StayInTouchSignature;
    }

    @JsonProperty("StayInTouchSignature")
    public void setStayInTouchSignature(String StayInTouchSignature) {
        this.StayInTouchSignature = StayInTouchSignature;
    }

    private String StayInTouchNote;

    @JsonProperty("StayInTouchNote")
    public String getStayInTouchNote() {
        return this.StayInTouchNote;
    }

    @JsonProperty("StayInTouchNote")
    public void setStayInTouchNote(String StayInTouchNote) {
        this.StayInTouchNote = StayInTouchNote;
    }

    private String Phone;

    @JsonProperty("Phone")
    public String getPhone() {
        return this.Phone;
    }

    @JsonProperty("Phone")
    public void setPhone(String Phone) {
        this.Phone = Phone;
    }

    private String Fax;

    @JsonProperty("Fax")
    public String getFax() {
        return this.Fax;
    }

    @JsonProperty("Fax")
    public void setFax(String Fax) {
        this.Fax = Fax;
    }

    private String MobilePhone;

    @JsonProperty("MobilePhone")
    public String getMobilePhone() {
        return this.MobilePhone;
    }

    @JsonProperty("MobilePhone")
    public void setMobilePhone(String MobilePhone) {
        this.MobilePhone = MobilePhone;
    }

    private String Alias;

    @JsonProperty("Alias")
    public String getAlias() {
        return this.Alias;
    }

    @JsonProperty("Alias")
    public void setAlias(String Alias) {
        this.Alias = Alias;
    }

    private String CommunityNickname;

    @JsonProperty("CommunityNickname")
    public String getCommunityNickname() {
        return this.CommunityNickname;
    }

    @JsonProperty("CommunityNickname")
    public void setCommunityNickname(String CommunityNickname) {
        this.CommunityNickname = CommunityNickname;
    }

    private String BadgeText;

    @JsonProperty("BadgeText")
    public String getBadgeText() {
        return this.BadgeText;
    }

    @JsonProperty("BadgeText")
    public void setBadgeText(String BadgeText) {
        this.BadgeText = BadgeText;
    }

    private Boolean IsActive;

    @JsonProperty("IsActive")
    public Boolean getIsActive() {
        return this.IsActive;
    }

    @JsonProperty("IsActive")
    public void setIsActive(Boolean IsActive) {
        this.IsActive = IsActive;
    }

    @XStreamConverter(PicklistEnumConverter.class)
    private User_TimeZoneSidKeyEnum TimeZoneSidKey;

    @JsonProperty("TimeZoneSidKey")
    public User_TimeZoneSidKeyEnum getTimeZoneSidKey() {
        return this.TimeZoneSidKey;
    }

    @JsonProperty("TimeZoneSidKey")
    public void setTimeZoneSidKey(User_TimeZoneSidKeyEnum TimeZoneSidKey) {
        this.TimeZoneSidKey = TimeZoneSidKey;
    }

    private String UserRoleId;

    @JsonProperty("UserRoleId")
    public String getUserRoleId() {
        return this.UserRoleId;
    }

    @JsonProperty("UserRoleId")
    public void setUserRoleId(String UserRoleId) {
        this.UserRoleId = UserRoleId;
    }

    @XStreamConverter(PicklistEnumConverter.class)
    private User_LocaleSidKeyEnum LocaleSidKey;

    @JsonProperty("LocaleSidKey")
    public User_LocaleSidKeyEnum getLocaleSidKey() {
        return this.LocaleSidKey;
    }

    @JsonProperty("LocaleSidKey")
    public void setLocaleSidKey(User_LocaleSidKeyEnum LocaleSidKey) {
        this.LocaleSidKey = LocaleSidKey;
    }

    private Boolean ReceivesInfoEmails;

    @JsonProperty("ReceivesInfoEmails")
    public Boolean getReceivesInfoEmails() {
        return this.ReceivesInfoEmails;
    }

    @JsonProperty("ReceivesInfoEmails")
    public void setReceivesInfoEmails(Boolean ReceivesInfoEmails) {
        this.ReceivesInfoEmails = ReceivesInfoEmails;
    }

    private Boolean ReceivesAdminInfoEmails;

    @JsonProperty("ReceivesAdminInfoEmails")
    public Boolean getReceivesAdminInfoEmails() {
        return this.ReceivesAdminInfoEmails;
    }

    @JsonProperty("ReceivesAdminInfoEmails")
    public void setReceivesAdminInfoEmails(Boolean ReceivesAdminInfoEmails) {
        this.ReceivesAdminInfoEmails = ReceivesAdminInfoEmails;
    }

    @XStreamConverter(PicklistEnumConverter.class)
    private User_EmailEncodingKeyEnum EmailEncodingKey;

    @JsonProperty("EmailEncodingKey")
    public User_EmailEncodingKeyEnum getEmailEncodingKey() {
        return this.EmailEncodingKey;
    }

    @JsonProperty("EmailEncodingKey")
    public void setEmailEncodingKey(User_EmailEncodingKeyEnum EmailEncodingKey) {
        this.EmailEncodingKey = EmailEncodingKey;
    }

    private String ProfileId;

    @JsonProperty("ProfileId")
    public String getProfileId() {
        return this.ProfileId;
    }

    @JsonProperty("ProfileId")
    public void setProfileId(String ProfileId) {
        this.ProfileId = ProfileId;
    }

    @XStreamConverter(PicklistEnumConverter.class)
    private User_UserTypeEnum UserType;

    @JsonProperty("UserType")
    public User_UserTypeEnum getUserType() {
        return this.UserType;
    }

    @JsonProperty("UserType")
    public void setUserType(User_UserTypeEnum UserType) {
        this.UserType = UserType;
    }

    @XStreamConverter(PicklistEnumConverter.class)
    private User_LanguageLocaleKeyEnum LanguageLocaleKey;

    @JsonProperty("LanguageLocaleKey")
    public User_LanguageLocaleKeyEnum getLanguageLocaleKey() {
        return this.LanguageLocaleKey;
    }

    @JsonProperty("LanguageLocaleKey")
    public void setLanguageLocaleKey(User_LanguageLocaleKeyEnum LanguageLocaleKey) {
        this.LanguageLocaleKey = LanguageLocaleKey;
    }

    private String EmployeeNumber;

    @JsonProperty("EmployeeNumber")
    public String getEmployeeNumber() {
        return this.EmployeeNumber;
    }

    @JsonProperty("EmployeeNumber")
    public void setEmployeeNumber(String EmployeeNumber) {
        this.EmployeeNumber = EmployeeNumber;
    }

    private String DelegatedApproverId;

    @JsonProperty("DelegatedApproverId")
    public String getDelegatedApproverId() {
        return this.DelegatedApproverId;
    }

    @JsonProperty("DelegatedApproverId")
    public void setDelegatedApproverId(String DelegatedApproverId) {
        this.DelegatedApproverId = DelegatedApproverId;
    }

    private String ManagerId;

    @JsonProperty("ManagerId")
    public String getManagerId() {
        return this.ManagerId;
    }

    @JsonProperty("ManagerId")
    public void setManagerId(String ManagerId) {
        this.ManagerId = ManagerId;
    }

    private java.time.ZonedDateTime LastLoginDate;

    @JsonProperty("LastLoginDate")
    public java.time.ZonedDateTime getLastLoginDate() {
        return this.LastLoginDate;
    }

    @JsonProperty("LastLoginDate")
    public void setLastLoginDate(java.time.ZonedDateTime LastLoginDate) {
        this.LastLoginDate = LastLoginDate;
    }

    private java.time.ZonedDateTime LastPasswordChangeDate;

    @JsonProperty("LastPasswordChangeDate")
    public java.time.ZonedDateTime getLastPasswordChangeDate() {
        return this.LastPasswordChangeDate;
    }

    @JsonProperty("LastPasswordChangeDate")
    public void setLastPasswordChangeDate(java.time.ZonedDateTime LastPasswordChangeDate) {
        this.LastPasswordChangeDate = LastPasswordChangeDate;
    }

    private java.time.ZonedDateTime OfflineTrialExpirationDate;

    @JsonProperty("OfflineTrialExpirationDate")
    public java.time.ZonedDateTime getOfflineTrialExpirationDate() {
        return this.OfflineTrialExpirationDate;
    }

    @JsonProperty("OfflineTrialExpirationDate")
    public void setOfflineTrialExpirationDate(java.time.ZonedDateTime OfflineTrialExpirationDate) {
        this.OfflineTrialExpirationDate = OfflineTrialExpirationDate;
    }

    private java.time.ZonedDateTime OfflinePdaTrialExpirationDate;

    @JsonProperty("OfflinePdaTrialExpirationDate")
    public java.time.ZonedDateTime getOfflinePdaTrialExpirationDate() {
        return this.OfflinePdaTrialExpirationDate;
    }

    @JsonProperty("OfflinePdaTrialExpirationDate")
    public void setOfflinePdaTrialExpirationDate(java.time.ZonedDateTime OfflinePdaTrialExpirationDate) {
        this.OfflinePdaTrialExpirationDate = OfflinePdaTrialExpirationDate;
    }

    private Boolean UserPermissionsMarketingUser;

    @JsonProperty("UserPermissionsMarketingUser")
    public Boolean getUserPermissionsMarketingUser() {
        return this.UserPermissionsMarketingUser;
    }

    @JsonProperty("UserPermissionsMarketingUser")
    public void setUserPermissionsMarketingUser(Boolean UserPermissionsMarketingUser) {
        this.UserPermissionsMarketingUser = UserPermissionsMarketingUser;
    }

    private Boolean UserPermissionsOfflineUser;

    @JsonProperty("UserPermissionsOfflineUser")
    public Boolean getUserPermissionsOfflineUser() {
        return this.UserPermissionsOfflineUser;
    }

    @JsonProperty("UserPermissionsOfflineUser")
    public void setUserPermissionsOfflineUser(Boolean UserPermissionsOfflineUser) {
        this.UserPermissionsOfflineUser = UserPermissionsOfflineUser;
    }

    private Boolean UserPermissionsCallCenterAutoLogin;

    @JsonProperty("UserPermissionsCallCenterAutoLogin")
    public Boolean getUserPermissionsCallCenterAutoLogin() {
        return this.UserPermissionsCallCenterAutoLogin;
    }

    @JsonProperty("UserPermissionsCallCenterAutoLogin")
    public void setUserPermissionsCallCenterAutoLogin(Boolean UserPermissionsCallCenterAutoLogin) {
        this.UserPermissionsCallCenterAutoLogin = UserPermissionsCallCenterAutoLogin;
    }

    private Boolean UserPermissionsMobileUser;

    @JsonProperty("UserPermissionsMobileUser")
    public Boolean getUserPermissionsMobileUser() {
        return this.UserPermissionsMobileUser;
    }

    @JsonProperty("UserPermissionsMobileUser")
    public void setUserPermissionsMobileUser(Boolean UserPermissionsMobileUser) {
        this.UserPermissionsMobileUser = UserPermissionsMobileUser;
    }

    private Boolean UserPermissionsSFContentUser;

    @JsonProperty("UserPermissionsSFContentUser")
    public Boolean getUserPermissionsSFContentUser() {
        return this.UserPermissionsSFContentUser;
    }

    @JsonProperty("UserPermissionsSFContentUser")
    public void setUserPermissionsSFContentUser(Boolean UserPermissionsSFContentUser) {
        this.UserPermissionsSFContentUser = UserPermissionsSFContentUser;
    }

    private Boolean UserPermissionsKnowledgeUser;

    @JsonProperty("UserPermissionsKnowledgeUser")
    public Boolean getUserPermissionsKnowledgeUser() {
        return this.UserPermissionsKnowledgeUser;
    }

    @JsonProperty("UserPermissionsKnowledgeUser")
    public void setUserPermissionsKnowledgeUser(Boolean UserPermissionsKnowledgeUser) {
        this.UserPermissionsKnowledgeUser = UserPermissionsKnowledgeUser;
    }

    private Boolean UserPermissionsInteractionUser;

    @JsonProperty("UserPermissionsInteractionUser")
    public Boolean getUserPermissionsInteractionUser() {
        return this.UserPermissionsInteractionUser;
    }

    @JsonProperty("UserPermissionsInteractionUser")
    public void setUserPermissionsInteractionUser(Boolean UserPermissionsInteractionUser) {
        this.UserPermissionsInteractionUser = UserPermissionsInteractionUser;
    }

    private Boolean UserPermissionsSupportUser;

    @JsonProperty("UserPermissionsSupportUser")
    public Boolean getUserPermissionsSupportUser() {
        return this.UserPermissionsSupportUser;
    }

    @JsonProperty("UserPermissionsSupportUser")
    public void setUserPermissionsSupportUser(Boolean UserPermissionsSupportUser) {
        this.UserPermissionsSupportUser = UserPermissionsSupportUser;
    }

    private Boolean UserPermissionsJigsawProspectingUser;

    @JsonProperty("UserPermissionsJigsawProspectingUser")
    public Boolean getUserPermissionsJigsawProspectingUser() {
        return this.UserPermissionsJigsawProspectingUser;
    }

    @JsonProperty("UserPermissionsJigsawProspectingUser")
    public void setUserPermissionsJigsawProspectingUser(Boolean UserPermissionsJigsawProspectingUser) {
        this.UserPermissionsJigsawProspectingUser = UserPermissionsJigsawProspectingUser;
    }

    private Boolean UserPermissionsSiteforceContributorUser;

    @JsonProperty("UserPermissionsSiteforceContributorUser")
    public Boolean getUserPermissionsSiteforceContributorUser() {
        return this.UserPermissionsSiteforceContributorUser;
    }

    @JsonProperty("UserPermissionsSiteforceContributorUser")
    public void setUserPermissionsSiteforceContributorUser(Boolean UserPermissionsSiteforceContributorUser) {
        this.UserPermissionsSiteforceContributorUser = UserPermissionsSiteforceContributorUser;
    }

    private Boolean UserPermissionsSiteforcePublisherUser;

    @JsonProperty("UserPermissionsSiteforcePublisherUser")
    public Boolean getUserPermissionsSiteforcePublisherUser() {
        return this.UserPermissionsSiteforcePublisherUser;
    }

    @JsonProperty("UserPermissionsSiteforcePublisherUser")
    public void setUserPermissionsSiteforcePublisherUser(Boolean UserPermissionsSiteforcePublisherUser) {
        this.UserPermissionsSiteforcePublisherUser = UserPermissionsSiteforcePublisherUser;
    }

    private Boolean UserPermissionsWorkDotComUserFeature;

    @JsonProperty("UserPermissionsWorkDotComUserFeature")
    public Boolean getUserPermissionsWorkDotComUserFeature() {
        return this.UserPermissionsWorkDotComUserFeature;
    }

    @JsonProperty("UserPermissionsWorkDotComUserFeature")
    public void setUserPermissionsWorkDotComUserFeature(Boolean UserPermissionsWorkDotComUserFeature) {
        this.UserPermissionsWorkDotComUserFeature = UserPermissionsWorkDotComUserFeature;
    }

    private Boolean ForecastEnabled;

    @JsonProperty("ForecastEnabled")
    public Boolean getForecastEnabled() {
        return this.ForecastEnabled;
    }

    @JsonProperty("ForecastEnabled")
    public void setForecastEnabled(Boolean ForecastEnabled) {
        this.ForecastEnabled = ForecastEnabled;
    }

    private Boolean UserPreferencesActivityRemindersPopup;

    @JsonProperty("UserPreferencesActivityRemindersPopup")
    public Boolean getUserPreferencesActivityRemindersPopup() {
        return this.UserPreferencesActivityRemindersPopup;
    }

    @JsonProperty("UserPreferencesActivityRemindersPopup")
    public void setUserPreferencesActivityRemindersPopup(Boolean UserPreferencesActivityRemindersPopup) {
        this.UserPreferencesActivityRemindersPopup = UserPreferencesActivityRemindersPopup;
    }

    private Boolean UserPreferencesEventRemindersCheckboxDefault;

    @JsonProperty("UserPreferencesEventRemindersCheckboxDefault")
    public Boolean getUserPreferencesEventRemindersCheckboxDefault() {
        return this.UserPreferencesEventRemindersCheckboxDefault;
    }

    @JsonProperty("UserPreferencesEventRemindersCheckboxDefault")
    public void setUserPreferencesEventRemindersCheckboxDefault(Boolean UserPreferencesEventRemindersCheckboxDefault) {
        this.UserPreferencesEventRemindersCheckboxDefault = UserPreferencesEventRemindersCheckboxDefault;
    }

    private Boolean UserPreferencesTaskRemindersCheckboxDefault;

    @JsonProperty("UserPreferencesTaskRemindersCheckboxDefault")
    public Boolean getUserPreferencesTaskRemindersCheckboxDefault() {
        return this.UserPreferencesTaskRemindersCheckboxDefault;
    }

    @JsonProperty("UserPreferencesTaskRemindersCheckboxDefault")
    public void setUserPreferencesTaskRemindersCheckboxDefault(Boolean UserPreferencesTaskRemindersCheckboxDefault) {
        this.UserPreferencesTaskRemindersCheckboxDefault = UserPreferencesTaskRemindersCheckboxDefault;
    }

    private Boolean UserPreferencesReminderSoundOff;

    @JsonProperty("UserPreferencesReminderSoundOff")
    public Boolean getUserPreferencesReminderSoundOff() {
        return this.UserPreferencesReminderSoundOff;
    }

    @JsonProperty("UserPreferencesReminderSoundOff")
    public void setUserPreferencesReminderSoundOff(Boolean UserPreferencesReminderSoundOff) {
        this.UserPreferencesReminderSoundOff = UserPreferencesReminderSoundOff;
    }

    private Boolean UserPreferencesDisableAllFeedsEmail;

    @JsonProperty("UserPreferencesDisableAllFeedsEmail")
    public Boolean getUserPreferencesDisableAllFeedsEmail() {
        return this.UserPreferencesDisableAllFeedsEmail;
    }

    @JsonProperty("UserPreferencesDisableAllFeedsEmail")
    public void setUserPreferencesDisableAllFeedsEmail(Boolean UserPreferencesDisableAllFeedsEmail) {
        this.UserPreferencesDisableAllFeedsEmail = UserPreferencesDisableAllFeedsEmail;
    }

    private Boolean UserPreferencesDisableFollowersEmail;

    @JsonProperty("UserPreferencesDisableFollowersEmail")
    public Boolean getUserPreferencesDisableFollowersEmail() {
        return this.UserPreferencesDisableFollowersEmail;
    }

    @JsonProperty("UserPreferencesDisableFollowersEmail")
    public void setUserPreferencesDisableFollowersEmail(Boolean UserPreferencesDisableFollowersEmail) {
        this.UserPreferencesDisableFollowersEmail = UserPreferencesDisableFollowersEmail;
    }

    private Boolean UserPreferencesDisableProfilePostEmail;

    @JsonProperty("UserPreferencesDisableProfilePostEmail")
    public Boolean getUserPreferencesDisableProfilePostEmail() {
        return this.UserPreferencesDisableProfilePostEmail;
    }

    @JsonProperty("UserPreferencesDisableProfilePostEmail")
    public void setUserPreferencesDisableProfilePostEmail(Boolean UserPreferencesDisableProfilePostEmail) {
        this.UserPreferencesDisableProfilePostEmail = UserPreferencesDisableProfilePostEmail;
    }

    private Boolean UserPreferencesDisableChangeCommentEmail;

    @JsonProperty("UserPreferencesDisableChangeCommentEmail")
    public Boolean getUserPreferencesDisableChangeCommentEmail() {
        return this.UserPreferencesDisableChangeCommentEmail;
    }

    @JsonProperty("UserPreferencesDisableChangeCommentEmail")
    public void setUserPreferencesDisableChangeCommentEmail(Boolean UserPreferencesDisableChangeCommentEmail) {
        this.UserPreferencesDisableChangeCommentEmail = UserPreferencesDisableChangeCommentEmail;
    }

    private Boolean UserPreferencesDisableLaterCommentEmail;

    @JsonProperty("UserPreferencesDisableLaterCommentEmail")
    public Boolean getUserPreferencesDisableLaterCommentEmail() {
        return this.UserPreferencesDisableLaterCommentEmail;
    }

    @JsonProperty("UserPreferencesDisableLaterCommentEmail")
    public void setUserPreferencesDisableLaterCommentEmail(Boolean UserPreferencesDisableLaterCommentEmail) {
        this.UserPreferencesDisableLaterCommentEmail = UserPreferencesDisableLaterCommentEmail;
    }

    private Boolean UserPreferencesDisProfPostCommentEmail;

    @JsonProperty("UserPreferencesDisProfPostCommentEmail")
    public Boolean getUserPreferencesDisProfPostCommentEmail() {
        return this.UserPreferencesDisProfPostCommentEmail;
    }

    @JsonProperty("UserPreferencesDisProfPostCommentEmail")
    public void setUserPreferencesDisProfPostCommentEmail(Boolean UserPreferencesDisProfPostCommentEmail) {
        this.UserPreferencesDisProfPostCommentEmail = UserPreferencesDisProfPostCommentEmail;
    }

    private Boolean UserPreferencesContentNoEmail;

    @JsonProperty("UserPreferencesContentNoEmail")
    public Boolean getUserPreferencesContentNoEmail() {
        return this.UserPreferencesContentNoEmail;
    }

    @JsonProperty("UserPreferencesContentNoEmail")
    public void setUserPreferencesContentNoEmail(Boolean UserPreferencesContentNoEmail) {
        this.UserPreferencesContentNoEmail = UserPreferencesContentNoEmail;
    }

    private Boolean UserPreferencesContentEmailAsAndWhen;

    @JsonProperty("UserPreferencesContentEmailAsAndWhen")
    public Boolean getUserPreferencesContentEmailAsAndWhen() {
        return this.UserPreferencesContentEmailAsAndWhen;
    }

    @JsonProperty("UserPreferencesContentEmailAsAndWhen")
    public void setUserPreferencesContentEmailAsAndWhen(Boolean UserPreferencesContentEmailAsAndWhen) {
        this.UserPreferencesContentEmailAsAndWhen = UserPreferencesContentEmailAsAndWhen;
    }

    private Boolean UserPreferencesApexPagesDeveloperMode;

    @JsonProperty("UserPreferencesApexPagesDeveloperMode")
    public Boolean getUserPreferencesApexPagesDeveloperMode() {
        return this.UserPreferencesApexPagesDeveloperMode;
    }

    @JsonProperty("UserPreferencesApexPagesDeveloperMode")
    public void setUserPreferencesApexPagesDeveloperMode(Boolean UserPreferencesApexPagesDeveloperMode) {
        this.UserPreferencesApexPagesDeveloperMode = UserPreferencesApexPagesDeveloperMode;
    }

    private Boolean UserPreferencesHideCSNGetChatterMobileTask;

    @JsonProperty("UserPreferencesHideCSNGetChatterMobileTask")
    public Boolean getUserPreferencesHideCSNGetChatterMobileTask() {
        return this.UserPreferencesHideCSNGetChatterMobileTask;
    }

    @JsonProperty("UserPreferencesHideCSNGetChatterMobileTask")
    public void setUserPreferencesHideCSNGetChatterMobileTask(Boolean UserPreferencesHideCSNGetChatterMobileTask) {
        this.UserPreferencesHideCSNGetChatterMobileTask = UserPreferencesHideCSNGetChatterMobileTask;
    }

    private Boolean UserPreferencesDisableMentionsPostEmail;

    @JsonProperty("UserPreferencesDisableMentionsPostEmail")
    public Boolean getUserPreferencesDisableMentionsPostEmail() {
        return this.UserPreferencesDisableMentionsPostEmail;
    }

    @JsonProperty("UserPreferencesDisableMentionsPostEmail")
    public void setUserPreferencesDisableMentionsPostEmail(Boolean UserPreferencesDisableMentionsPostEmail) {
        this.UserPreferencesDisableMentionsPostEmail = UserPreferencesDisableMentionsPostEmail;
    }

    private Boolean UserPreferencesDisMentionsCommentEmail;

    @JsonProperty("UserPreferencesDisMentionsCommentEmail")
    public Boolean getUserPreferencesDisMentionsCommentEmail() {
        return this.UserPreferencesDisMentionsCommentEmail;
    }

    @JsonProperty("UserPreferencesDisMentionsCommentEmail")
    public void setUserPreferencesDisMentionsCommentEmail(Boolean UserPreferencesDisMentionsCommentEmail) {
        this.UserPreferencesDisMentionsCommentEmail = UserPreferencesDisMentionsCommentEmail;
    }

    private Boolean UserPreferencesHideCSNDesktopTask;

    @JsonProperty("UserPreferencesHideCSNDesktopTask")
    public Boolean getUserPreferencesHideCSNDesktopTask() {
        return this.UserPreferencesHideCSNDesktopTask;
    }

    @JsonProperty("UserPreferencesHideCSNDesktopTask")
    public void setUserPreferencesHideCSNDesktopTask(Boolean UserPreferencesHideCSNDesktopTask) {
        this.UserPreferencesHideCSNDesktopTask = UserPreferencesHideCSNDesktopTask;
    }

    private Boolean UserPreferencesHideChatterOnboardingSplash;

    @JsonProperty("UserPreferencesHideChatterOnboardingSplash")
    public Boolean getUserPreferencesHideChatterOnboardingSplash() {
        return this.UserPreferencesHideChatterOnboardingSplash;
    }

    @JsonProperty("UserPreferencesHideChatterOnboardingSplash")
    public void setUserPreferencesHideChatterOnboardingSplash(Boolean UserPreferencesHideChatterOnboardingSplash) {
        this.UserPreferencesHideChatterOnboardingSplash = UserPreferencesHideChatterOnboardingSplash;
    }

    private Boolean UserPreferencesHideSecondChatterOnboardingSplash;

    @JsonProperty("UserPreferencesHideSecondChatterOnboardingSplash")
    public Boolean getUserPreferencesHideSecondChatterOnboardingSplash() {
        return this.UserPreferencesHideSecondChatterOnboardingSplash;
    }

    @JsonProperty("UserPreferencesHideSecondChatterOnboardingSplash")
    public void setUserPreferencesHideSecondChatterOnboardingSplash(Boolean UserPreferencesHideSecondChatterOnboardingSplash) {
        this.UserPreferencesHideSecondChatterOnboardingSplash = UserPreferencesHideSecondChatterOnboardingSplash;
    }

    private Boolean UserPreferencesDisCommentAfterLikeEmail;

    @JsonProperty("UserPreferencesDisCommentAfterLikeEmail")
    public Boolean getUserPreferencesDisCommentAfterLikeEmail() {
        return this.UserPreferencesDisCommentAfterLikeEmail;
    }

    @JsonProperty("UserPreferencesDisCommentAfterLikeEmail")
    public void setUserPreferencesDisCommentAfterLikeEmail(Boolean UserPreferencesDisCommentAfterLikeEmail) {
        this.UserPreferencesDisCommentAfterLikeEmail = UserPreferencesDisCommentAfterLikeEmail;
    }

    private Boolean UserPreferencesDisableLikeEmail;

    @JsonProperty("UserPreferencesDisableLikeEmail")
    public Boolean getUserPreferencesDisableLikeEmail() {
        return this.UserPreferencesDisableLikeEmail;
    }

    @JsonProperty("UserPreferencesDisableLikeEmail")
    public void setUserPreferencesDisableLikeEmail(Boolean UserPreferencesDisableLikeEmail) {
        this.UserPreferencesDisableLikeEmail = UserPreferencesDisableLikeEmail;
    }

    private Boolean UserPreferencesSortFeedByComment;

    @JsonProperty("UserPreferencesSortFeedByComment")
    public Boolean getUserPreferencesSortFeedByComment() {
        return this.UserPreferencesSortFeedByComment;
    }

    @JsonProperty("UserPreferencesSortFeedByComment")
    public void setUserPreferencesSortFeedByComment(Boolean UserPreferencesSortFeedByComment) {
        this.UserPreferencesSortFeedByComment = UserPreferencesSortFeedByComment;
    }

    private Boolean UserPreferencesDisableMessageEmail;

    @JsonProperty("UserPreferencesDisableMessageEmail")
    public Boolean getUserPreferencesDisableMessageEmail() {
        return this.UserPreferencesDisableMessageEmail;
    }

    @JsonProperty("UserPreferencesDisableMessageEmail")
    public void setUserPreferencesDisableMessageEmail(Boolean UserPreferencesDisableMessageEmail) {
        this.UserPreferencesDisableMessageEmail = UserPreferencesDisableMessageEmail;
    }

    private Boolean UserPreferencesJigsawListUser;

    @JsonProperty("UserPreferencesJigsawListUser")
    public Boolean getUserPreferencesJigsawListUser() {
        return this.UserPreferencesJigsawListUser;
    }

    @JsonProperty("UserPreferencesJigsawListUser")
    public void setUserPreferencesJigsawListUser(Boolean UserPreferencesJigsawListUser) {
        this.UserPreferencesJigsawListUser = UserPreferencesJigsawListUser;
    }

    private Boolean UserPreferencesDisableBookmarkEmail;

    @JsonProperty("UserPreferencesDisableBookmarkEmail")
    public Boolean getUserPreferencesDisableBookmarkEmail() {
        return this.UserPreferencesDisableBookmarkEmail;
    }

    @JsonProperty("UserPreferencesDisableBookmarkEmail")
    public void setUserPreferencesDisableBookmarkEmail(Boolean UserPreferencesDisableBookmarkEmail) {
        this.UserPreferencesDisableBookmarkEmail = UserPreferencesDisableBookmarkEmail;
    }

    private Boolean UserPreferencesDisableSharePostEmail;

    @JsonProperty("UserPreferencesDisableSharePostEmail")
    public Boolean getUserPreferencesDisableSharePostEmail() {
        return this.UserPreferencesDisableSharePostEmail;
    }

    @JsonProperty("UserPreferencesDisableSharePostEmail")
    public void setUserPreferencesDisableSharePostEmail(Boolean UserPreferencesDisableSharePostEmail) {
        this.UserPreferencesDisableSharePostEmail = UserPreferencesDisableSharePostEmail;
    }

    private Boolean UserPreferencesEnableAutoSubForFeeds;

    @JsonProperty("UserPreferencesEnableAutoSubForFeeds")
    public Boolean getUserPreferencesEnableAutoSubForFeeds() {
        return this.UserPreferencesEnableAutoSubForFeeds;
    }

    @JsonProperty("UserPreferencesEnableAutoSubForFeeds")
    public void setUserPreferencesEnableAutoSubForFeeds(Boolean UserPreferencesEnableAutoSubForFeeds) {
        this.UserPreferencesEnableAutoSubForFeeds = UserPreferencesEnableAutoSubForFeeds;
    }

    private Boolean UserPreferencesDisableFileShareNotificationsForApi;

    @JsonProperty("UserPreferencesDisableFileShareNotificationsForApi")
    public Boolean getUserPreferencesDisableFileShareNotificationsForApi() {
        return this.UserPreferencesDisableFileShareNotificationsForApi;
    }

    @JsonProperty("UserPreferencesDisableFileShareNotificationsForApi")
    public void setUserPreferencesDisableFileShareNotificationsForApi(Boolean UserPreferencesDisableFileShareNotificationsForApi) {
        this.UserPreferencesDisableFileShareNotificationsForApi = UserPreferencesDisableFileShareNotificationsForApi;
    }

    private Boolean UserPreferencesShowTitleToExternalUsers;

    @JsonProperty("UserPreferencesShowTitleToExternalUsers")
    public Boolean getUserPreferencesShowTitleToExternalUsers() {
        return this.UserPreferencesShowTitleToExternalUsers;
    }

    @JsonProperty("UserPreferencesShowTitleToExternalUsers")
    public void setUserPreferencesShowTitleToExternalUsers(Boolean UserPreferencesShowTitleToExternalUsers) {
        this.UserPreferencesShowTitleToExternalUsers = UserPreferencesShowTitleToExternalUsers;
    }

    private Boolean UserPreferencesShowManagerToExternalUsers;

    @JsonProperty("UserPreferencesShowManagerToExternalUsers")
    public Boolean getUserPreferencesShowManagerToExternalUsers() {
        return this.UserPreferencesShowManagerToExternalUsers;
    }

    @JsonProperty("UserPreferencesShowManagerToExternalUsers")
    public void setUserPreferencesShowManagerToExternalUsers(Boolean UserPreferencesShowManagerToExternalUsers) {
        this.UserPreferencesShowManagerToExternalUsers = UserPreferencesShowManagerToExternalUsers;
    }

    private Boolean UserPreferencesShowEmailToExternalUsers;

    @JsonProperty("UserPreferencesShowEmailToExternalUsers")
    public Boolean getUserPreferencesShowEmailToExternalUsers() {
        return this.UserPreferencesShowEmailToExternalUsers;
    }

    @JsonProperty("UserPreferencesShowEmailToExternalUsers")
    public void setUserPreferencesShowEmailToExternalUsers(Boolean UserPreferencesShowEmailToExternalUsers) {
        this.UserPreferencesShowEmailToExternalUsers = UserPreferencesShowEmailToExternalUsers;
    }

    private Boolean UserPreferencesShowWorkPhoneToExternalUsers;

    @JsonProperty("UserPreferencesShowWorkPhoneToExternalUsers")
    public Boolean getUserPreferencesShowWorkPhoneToExternalUsers() {
        return this.UserPreferencesShowWorkPhoneToExternalUsers;
    }

    @JsonProperty("UserPreferencesShowWorkPhoneToExternalUsers")
    public void setUserPreferencesShowWorkPhoneToExternalUsers(Boolean UserPreferencesShowWorkPhoneToExternalUsers) {
        this.UserPreferencesShowWorkPhoneToExternalUsers = UserPreferencesShowWorkPhoneToExternalUsers;
    }

    private Boolean UserPreferencesShowMobilePhoneToExternalUsers;

    @JsonProperty("UserPreferencesShowMobilePhoneToExternalUsers")
    public Boolean getUserPreferencesShowMobilePhoneToExternalUsers() {
        return this.UserPreferencesShowMobilePhoneToExternalUsers;
    }

    @JsonProperty("UserPreferencesShowMobilePhoneToExternalUsers")
    public void setUserPreferencesShowMobilePhoneToExternalUsers(Boolean UserPreferencesShowMobilePhoneToExternalUsers) {
        this.UserPreferencesShowMobilePhoneToExternalUsers = UserPreferencesShowMobilePhoneToExternalUsers;
    }

    private Boolean UserPreferencesShowFaxToExternalUsers;

    @JsonProperty("UserPreferencesShowFaxToExternalUsers")
    public Boolean getUserPreferencesShowFaxToExternalUsers() {
        return this.UserPreferencesShowFaxToExternalUsers;
    }

    @JsonProperty("UserPreferencesShowFaxToExternalUsers")
    public void setUserPreferencesShowFaxToExternalUsers(Boolean UserPreferencesShowFaxToExternalUsers) {
        this.UserPreferencesShowFaxToExternalUsers = UserPreferencesShowFaxToExternalUsers;
    }

    private Boolean UserPreferencesShowStreetAddressToExternalUsers;

    @JsonProperty("UserPreferencesShowStreetAddressToExternalUsers")
    public Boolean getUserPreferencesShowStreetAddressToExternalUsers() {
        return this.UserPreferencesShowStreetAddressToExternalUsers;
    }

    @JsonProperty("UserPreferencesShowStreetAddressToExternalUsers")
    public void setUserPreferencesShowStreetAddressToExternalUsers(Boolean UserPreferencesShowStreetAddressToExternalUsers) {
        this.UserPreferencesShowStreetAddressToExternalUsers = UserPreferencesShowStreetAddressToExternalUsers;
    }

    private Boolean UserPreferencesShowCityToExternalUsers;

    @JsonProperty("UserPreferencesShowCityToExternalUsers")
    public Boolean getUserPreferencesShowCityToExternalUsers() {
        return this.UserPreferencesShowCityToExternalUsers;
    }

    @JsonProperty("UserPreferencesShowCityToExternalUsers")
    public void setUserPreferencesShowCityToExternalUsers(Boolean UserPreferencesShowCityToExternalUsers) {
        this.UserPreferencesShowCityToExternalUsers = UserPreferencesShowCityToExternalUsers;
    }

    private Boolean UserPreferencesShowStateToExternalUsers;

    @JsonProperty("UserPreferencesShowStateToExternalUsers")
    public Boolean getUserPreferencesShowStateToExternalUsers() {
        return this.UserPreferencesShowStateToExternalUsers;
    }

    @JsonProperty("UserPreferencesShowStateToExternalUsers")
    public void setUserPreferencesShowStateToExternalUsers(Boolean UserPreferencesShowStateToExternalUsers) {
        this.UserPreferencesShowStateToExternalUsers = UserPreferencesShowStateToExternalUsers;
    }

    private Boolean UserPreferencesShowPostalCodeToExternalUsers;

    @JsonProperty("UserPreferencesShowPostalCodeToExternalUsers")
    public Boolean getUserPreferencesShowPostalCodeToExternalUsers() {
        return this.UserPreferencesShowPostalCodeToExternalUsers;
    }

    @JsonProperty("UserPreferencesShowPostalCodeToExternalUsers")
    public void setUserPreferencesShowPostalCodeToExternalUsers(Boolean UserPreferencesShowPostalCodeToExternalUsers) {
        this.UserPreferencesShowPostalCodeToExternalUsers = UserPreferencesShowPostalCodeToExternalUsers;
    }

    private Boolean UserPreferencesShowCountryToExternalUsers;

    @JsonProperty("UserPreferencesShowCountryToExternalUsers")
    public Boolean getUserPreferencesShowCountryToExternalUsers() {
        return this.UserPreferencesShowCountryToExternalUsers;
    }

    @JsonProperty("UserPreferencesShowCountryToExternalUsers")
    public void setUserPreferencesShowCountryToExternalUsers(Boolean UserPreferencesShowCountryToExternalUsers) {
        this.UserPreferencesShowCountryToExternalUsers = UserPreferencesShowCountryToExternalUsers;
    }

    private Boolean UserPreferencesShowProfilePicToGuestUsers;

    @JsonProperty("UserPreferencesShowProfilePicToGuestUsers")
    public Boolean getUserPreferencesShowProfilePicToGuestUsers() {
        return this.UserPreferencesShowProfilePicToGuestUsers;
    }

    @JsonProperty("UserPreferencesShowProfilePicToGuestUsers")
    public void setUserPreferencesShowProfilePicToGuestUsers(Boolean UserPreferencesShowProfilePicToGuestUsers) {
        this.UserPreferencesShowProfilePicToGuestUsers = UserPreferencesShowProfilePicToGuestUsers;
    }

    private Boolean UserPreferencesShowTitleToGuestUsers;

    @JsonProperty("UserPreferencesShowTitleToGuestUsers")
    public Boolean getUserPreferencesShowTitleToGuestUsers() {
        return this.UserPreferencesShowTitleToGuestUsers;
    }

    @JsonProperty("UserPreferencesShowTitleToGuestUsers")
    public void setUserPreferencesShowTitleToGuestUsers(Boolean UserPreferencesShowTitleToGuestUsers) {
        this.UserPreferencesShowTitleToGuestUsers = UserPreferencesShowTitleToGuestUsers;
    }

    private Boolean UserPreferencesShowCityToGuestUsers;

    @JsonProperty("UserPreferencesShowCityToGuestUsers")
    public Boolean getUserPreferencesShowCityToGuestUsers() {
        return this.UserPreferencesShowCityToGuestUsers;
    }

    @JsonProperty("UserPreferencesShowCityToGuestUsers")
    public void setUserPreferencesShowCityToGuestUsers(Boolean UserPreferencesShowCityToGuestUsers) {
        this.UserPreferencesShowCityToGuestUsers = UserPreferencesShowCityToGuestUsers;
    }

    private Boolean UserPreferencesShowStateToGuestUsers;

    @JsonProperty("UserPreferencesShowStateToGuestUsers")
    public Boolean getUserPreferencesShowStateToGuestUsers() {
        return this.UserPreferencesShowStateToGuestUsers;
    }

    @JsonProperty("UserPreferencesShowStateToGuestUsers")
    public void setUserPreferencesShowStateToGuestUsers(Boolean UserPreferencesShowStateToGuestUsers) {
        this.UserPreferencesShowStateToGuestUsers = UserPreferencesShowStateToGuestUsers;
    }

    private Boolean UserPreferencesShowPostalCodeToGuestUsers;

    @JsonProperty("UserPreferencesShowPostalCodeToGuestUsers")
    public Boolean getUserPreferencesShowPostalCodeToGuestUsers() {
        return this.UserPreferencesShowPostalCodeToGuestUsers;
    }

    @JsonProperty("UserPreferencesShowPostalCodeToGuestUsers")
    public void setUserPreferencesShowPostalCodeToGuestUsers(Boolean UserPreferencesShowPostalCodeToGuestUsers) {
        this.UserPreferencesShowPostalCodeToGuestUsers = UserPreferencesShowPostalCodeToGuestUsers;
    }

    private Boolean UserPreferencesShowCountryToGuestUsers;

    @JsonProperty("UserPreferencesShowCountryToGuestUsers")
    public Boolean getUserPreferencesShowCountryToGuestUsers() {
        return this.UserPreferencesShowCountryToGuestUsers;
    }

    @JsonProperty("UserPreferencesShowCountryToGuestUsers")
    public void setUserPreferencesShowCountryToGuestUsers(Boolean UserPreferencesShowCountryToGuestUsers) {
        this.UserPreferencesShowCountryToGuestUsers = UserPreferencesShowCountryToGuestUsers;
    }

    private Boolean UserPreferencesDisableFeedbackEmail;

    @JsonProperty("UserPreferencesDisableFeedbackEmail")
    public Boolean getUserPreferencesDisableFeedbackEmail() {
        return this.UserPreferencesDisableFeedbackEmail;
    }

    @JsonProperty("UserPreferencesDisableFeedbackEmail")
    public void setUserPreferencesDisableFeedbackEmail(Boolean UserPreferencesDisableFeedbackEmail) {
        this.UserPreferencesDisableFeedbackEmail = UserPreferencesDisableFeedbackEmail;
    }

    private Boolean UserPreferencesDisableWorkEmail;

    @JsonProperty("UserPreferencesDisableWorkEmail")
    public Boolean getUserPreferencesDisableWorkEmail() {
        return this.UserPreferencesDisableWorkEmail;
    }

    @JsonProperty("UserPreferencesDisableWorkEmail")
    public void setUserPreferencesDisableWorkEmail(Boolean UserPreferencesDisableWorkEmail) {
        this.UserPreferencesDisableWorkEmail = UserPreferencesDisableWorkEmail;
    }

    private Boolean UserPreferencesHideS1BrowserUI;

    @JsonProperty("UserPreferencesHideS1BrowserUI")
    public Boolean getUserPreferencesHideS1BrowserUI() {
        return this.UserPreferencesHideS1BrowserUI;
    }

    @JsonProperty("UserPreferencesHideS1BrowserUI")
    public void setUserPreferencesHideS1BrowserUI(Boolean UserPreferencesHideS1BrowserUI) {
        this.UserPreferencesHideS1BrowserUI = UserPreferencesHideS1BrowserUI;
    }

    private Boolean UserPreferencesDisableEndorsementEmail;

    @JsonProperty("UserPreferencesDisableEndorsementEmail")
    public Boolean getUserPreferencesDisableEndorsementEmail() {
        return this.UserPreferencesDisableEndorsementEmail;
    }

    @JsonProperty("UserPreferencesDisableEndorsementEmail")
    public void setUserPreferencesDisableEndorsementEmail(Boolean UserPreferencesDisableEndorsementEmail) {
        this.UserPreferencesDisableEndorsementEmail = UserPreferencesDisableEndorsementEmail;
    }

    private Boolean UserPreferencesPathAssistantCollapsed;

    @JsonProperty("UserPreferencesPathAssistantCollapsed")
    public Boolean getUserPreferencesPathAssistantCollapsed() {
        return this.UserPreferencesPathAssistantCollapsed;
    }

    @JsonProperty("UserPreferencesPathAssistantCollapsed")
    public void setUserPreferencesPathAssistantCollapsed(Boolean UserPreferencesPathAssistantCollapsed) {
        this.UserPreferencesPathAssistantCollapsed = UserPreferencesPathAssistantCollapsed;
    }

    private Boolean UserPreferencesCacheDiagnostics;

    @JsonProperty("UserPreferencesCacheDiagnostics")
    public Boolean getUserPreferencesCacheDiagnostics() {
        return this.UserPreferencesCacheDiagnostics;
    }

    @JsonProperty("UserPreferencesCacheDiagnostics")
    public void setUserPreferencesCacheDiagnostics(Boolean UserPreferencesCacheDiagnostics) {
        this.UserPreferencesCacheDiagnostics = UserPreferencesCacheDiagnostics;
    }

    private Boolean UserPreferencesShowEmailToGuestUsers;

    @JsonProperty("UserPreferencesShowEmailToGuestUsers")
    public Boolean getUserPreferencesShowEmailToGuestUsers() {
        return this.UserPreferencesShowEmailToGuestUsers;
    }

    @JsonProperty("UserPreferencesShowEmailToGuestUsers")
    public void setUserPreferencesShowEmailToGuestUsers(Boolean UserPreferencesShowEmailToGuestUsers) {
        this.UserPreferencesShowEmailToGuestUsers = UserPreferencesShowEmailToGuestUsers;
    }

    private Boolean UserPreferencesShowManagerToGuestUsers;

    @JsonProperty("UserPreferencesShowManagerToGuestUsers")
    public Boolean getUserPreferencesShowManagerToGuestUsers() {
        return this.UserPreferencesShowManagerToGuestUsers;
    }

    @JsonProperty("UserPreferencesShowManagerToGuestUsers")
    public void setUserPreferencesShowManagerToGuestUsers(Boolean UserPreferencesShowManagerToGuestUsers) {
        this.UserPreferencesShowManagerToGuestUsers = UserPreferencesShowManagerToGuestUsers;
    }

    private Boolean UserPreferencesShowWorkPhoneToGuestUsers;

    @JsonProperty("UserPreferencesShowWorkPhoneToGuestUsers")
    public Boolean getUserPreferencesShowWorkPhoneToGuestUsers() {
        return this.UserPreferencesShowWorkPhoneToGuestUsers;
    }

    @JsonProperty("UserPreferencesShowWorkPhoneToGuestUsers")
    public void setUserPreferencesShowWorkPhoneToGuestUsers(Boolean UserPreferencesShowWorkPhoneToGuestUsers) {
        this.UserPreferencesShowWorkPhoneToGuestUsers = UserPreferencesShowWorkPhoneToGuestUsers;
    }

    private Boolean UserPreferencesShowMobilePhoneToGuestUsers;

    @JsonProperty("UserPreferencesShowMobilePhoneToGuestUsers")
    public Boolean getUserPreferencesShowMobilePhoneToGuestUsers() {
        return this.UserPreferencesShowMobilePhoneToGuestUsers;
    }

    @JsonProperty("UserPreferencesShowMobilePhoneToGuestUsers")
    public void setUserPreferencesShowMobilePhoneToGuestUsers(Boolean UserPreferencesShowMobilePhoneToGuestUsers) {
        this.UserPreferencesShowMobilePhoneToGuestUsers = UserPreferencesShowMobilePhoneToGuestUsers;
    }

    private Boolean UserPreferencesShowFaxToGuestUsers;

    @JsonProperty("UserPreferencesShowFaxToGuestUsers")
    public Boolean getUserPreferencesShowFaxToGuestUsers() {
        return this.UserPreferencesShowFaxToGuestUsers;
    }

    @JsonProperty("UserPreferencesShowFaxToGuestUsers")
    public void setUserPreferencesShowFaxToGuestUsers(Boolean UserPreferencesShowFaxToGuestUsers) {
        this.UserPreferencesShowFaxToGuestUsers = UserPreferencesShowFaxToGuestUsers;
    }

    private Boolean UserPreferencesShowStreetAddressToGuestUsers;

    @JsonProperty("UserPreferencesShowStreetAddressToGuestUsers")
    public Boolean getUserPreferencesShowStreetAddressToGuestUsers() {
        return this.UserPreferencesShowStreetAddressToGuestUsers;
    }

    @JsonProperty("UserPreferencesShowStreetAddressToGuestUsers")
    public void setUserPreferencesShowStreetAddressToGuestUsers(Boolean UserPreferencesShowStreetAddressToGuestUsers) {
        this.UserPreferencesShowStreetAddressToGuestUsers = UserPreferencesShowStreetAddressToGuestUsers;
    }

    private Boolean UserPreferencesLightningExperiencePreferred;

    @JsonProperty("UserPreferencesLightningExperiencePreferred")
    public Boolean getUserPreferencesLightningExperiencePreferred() {
        return this.UserPreferencesLightningExperiencePreferred;
    }

    @JsonProperty("UserPreferencesLightningExperiencePreferred")
    public void setUserPreferencesLightningExperiencePreferred(Boolean UserPreferencesLightningExperiencePreferred) {
        this.UserPreferencesLightningExperiencePreferred = UserPreferencesLightningExperiencePreferred;
    }

    private String ContactId;

    @JsonProperty("ContactId")
    public String getContactId() {
        return this.ContactId;
    }

    @JsonProperty("ContactId")
    public void setContactId(String ContactId) {
        this.ContactId = ContactId;
    }

    private String AccountId;

    @JsonProperty("AccountId")
    public String getAccountId() {
        return this.AccountId;
    }

    @JsonProperty("AccountId")
    public void setAccountId(String AccountId) {
        this.AccountId = AccountId;
    }

    private String CallCenterId;

    @JsonProperty("CallCenterId")
    public String getCallCenterId() {
        return this.CallCenterId;
    }

    @JsonProperty("CallCenterId")
    public void setCallCenterId(String CallCenterId) {
        this.CallCenterId = CallCenterId;
    }

    private String Extension;

    @JsonProperty("Extension")
    public String getExtension() {
        return this.Extension;
    }

    @JsonProperty("Extension")
    public void setExtension(String Extension) {
        this.Extension = Extension;
    }

    private String FederationIdentifier;

    @JsonProperty("FederationIdentifier")
    public String getFederationIdentifier() {
        return this.FederationIdentifier;
    }

    @JsonProperty("FederationIdentifier")
    public void setFederationIdentifier(String FederationIdentifier) {
        this.FederationIdentifier = FederationIdentifier;
    }

    private String AboutMe;

    @JsonProperty("AboutMe")
    public String getAboutMe() {
        return this.AboutMe;
    }

    @JsonProperty("AboutMe")
    public void setAboutMe(String AboutMe) {
        this.AboutMe = AboutMe;
    }

    private String FullPhotoUrl;

    @JsonProperty("FullPhotoUrl")
    public String getFullPhotoUrl() {
        return this.FullPhotoUrl;
    }

    @JsonProperty("FullPhotoUrl")
    public void setFullPhotoUrl(String FullPhotoUrl) {
        this.FullPhotoUrl = FullPhotoUrl;
    }

    private String SmallPhotoUrl;

    @JsonProperty("SmallPhotoUrl")
    public String getSmallPhotoUrl() {
        return this.SmallPhotoUrl;
    }

    @JsonProperty("SmallPhotoUrl")
    public void setSmallPhotoUrl(String SmallPhotoUrl) {
        this.SmallPhotoUrl = SmallPhotoUrl;
    }

    @XStreamConverter(PicklistEnumConverter.class)
    private User_DigestFrequencyEnum DigestFrequency;

    @JsonProperty("DigestFrequency")
    public User_DigestFrequencyEnum getDigestFrequency() {
        return this.DigestFrequency;
    }

    @JsonProperty("DigestFrequency")
    public void setDigestFrequency(User_DigestFrequencyEnum DigestFrequency) {
        this.DigestFrequency = DigestFrequency;
    }

    @XStreamConverter(PicklistEnumConverter.class)
    private User_DefaultGroupNotificationFrequencyEnum DefaultGroupNotificationFrequency;

    @JsonProperty("DefaultGroupNotificationFrequency")
    public User_DefaultGroupNotificationFrequencyEnum getDefaultGroupNotificationFrequency() {
        return this.DefaultGroupNotificationFrequency;
    }

    @JsonProperty("DefaultGroupNotificationFrequency")
    public void setDefaultGroupNotificationFrequency(User_DefaultGroupNotificationFrequencyEnum DefaultGroupNotificationFrequency) {
        this.DefaultGroupNotificationFrequency = DefaultGroupNotificationFrequency;
    }

    private Integer JigsawImportLimitOverride;

    @JsonProperty("JigsawImportLimitOverride")
    public Integer getJigsawImportLimitOverride() {
        return this.JigsawImportLimitOverride;
    }

    @JsonProperty("JigsawImportLimitOverride")
    public void setJigsawImportLimitOverride(Integer JigsawImportLimitOverride) {
        this.JigsawImportLimitOverride = JigsawImportLimitOverride;
    }

 
    @Override
    public final SObjectDescription description() {
        return DESCRIPTION;
    }

    private static SObjectDescription createSObjectDescription() {
        final SObjectDescription description = new SObjectDescription();



        final List<SObjectField> fields1 = new ArrayList<>();
        description.setFields(fields1);

        final SObjectField sObjectField1 = createField("Id", "User ID", "id", "tns:ID", 18, false, false, false, false, false, false, true);
        fields1.add(sObjectField1);
        final SObjectField sObjectField2 = createField("Username", "Username", "string", "xsd:string", 80, false, false, false, false, false, false, true);
        fields1.add(sObjectField2);
        final SObjectField sObjectField3 = createField("LastName", "Last Name", "string", "xsd:string", 80, false, false, false, false, false, false, false);
        fields1.add(sObjectField3);
        final SObjectField sObjectField4 = createField("FirstName", "First Name", "string", "xsd:string", 40, false, true, false, false, false, false, false);
        fields1.add(sObjectField4);
        final SObjectField sObjectField5 = createField("Name", "Full Name", "string", "xsd:string", 121, false, false, true, false, false, false, false);
        fields1.add(sObjectField5);
        final SObjectField sObjectField6 = createField("CompanyName", "Company Name", "string", "xsd:string", 80, false, true, false, false, false, false, false);
        fields1.add(sObjectField6);
        final SObjectField sObjectField7 = createField("Division", "Division", "string", "xsd:string", 80, false, true, false, false, false, false, false);
        fields1.add(sObjectField7);
        final SObjectField sObjectField8 = createField("Department", "Department", "string", "xsd:string", 80, false, true, false, false, false, false, false);
        fields1.add(sObjectField8);
        final SObjectField sObjectField9 = createField("Title", "Title", "string", "xsd:string", 80, false, true, false, false, false, false, false);
        fields1.add(sObjectField9);
        final SObjectField sObjectField10 = createField("Street", "Street", "textarea", "xsd:string", 255, false, true, false, false, false, false, false);
        fields1.add(sObjectField10);
        final SObjectField sObjectField11 = createField("City", "City", "string", "xsd:string", 40, false, true, false, false, false, false, false);
        fields1.add(sObjectField11);
        final SObjectField sObjectField12 = createField("State", "State/Province", "string", "xsd:string", 80, false, true, false, false, false, false, false);
        fields1.add(sObjectField12);
        final SObjectField sObjectField13 = createField("PostalCode", "Zip/Postal Code", "string", "xsd:string", 20, false, true, false, false, false, false, false);
        fields1.add(sObjectField13);
        final SObjectField sObjectField14 = createField("Country", "Country", "string", "xsd:string", 80, false, true, false, false, false, false, false);
        fields1.add(sObjectField14);
        final SObjectField sObjectField15 = createField("Latitude", "Latitude", "double", "xsd:double", 0, false, true, false, false, false, false, false);
        fields1.add(sObjectField15);
        final SObjectField sObjectField16 = createField("Longitude", "Longitude", "double", "xsd:double", 0, false, true, false, false, false, false, false);
        fields1.add(sObjectField16);
        final SObjectField sObjectField17 = createField("Address", "Address", "address", "urn:address", 0, false, true, false, false, false, false, false);
        fields1.add(sObjectField17);
        final SObjectField sObjectField18 = createField("Email", "Email", "email", "xsd:string", 128, false, false, false, false, false, false, true);
        fields1.add(sObjectField18);
        final SObjectField sObjectField19 = createField("EmailPreferencesAutoBcc", "AutoBcc", "boolean", "xsd:boolean", 0, false, false, false, false, false, false, false);
        fields1.add(sObjectField19);
        final SObjectField sObjectField20 = createField("EmailPreferencesAutoBccStayInTouch", "AutoBccStayInTouch", "boolean", "xsd:boolean", 0, false, false, false, false, false, false, false);
        fields1.add(sObjectField20);
        final SObjectField sObjectField21 = createField("EmailPreferencesStayInTouchReminder", "StayInTouchReminder", "boolean", "xsd:boolean", 0, false, false, false, false, false, false, false);
        fields1.add(sObjectField21);
        final SObjectField sObjectField22 = createField("SenderEmail", "Email Sender Address", "email", "xsd:string", 80, false, true, false, false, false, false, false);
        fields1.add(sObjectField22);
        final SObjectField sObjectField23 = createField("SenderName", "Email Sender Name", "string", "xsd:string", 80, false, true, false, false, false, false, false);
        fields1.add(sObjectField23);
        final SObjectField sObjectField24 = createField("Signature", "Email Signature", "textarea", "xsd:string", 1333, false, true, false, false, false, false, false);
        fields1.add(sObjectField24);
        final SObjectField sObjectField25 = createField("StayInTouchSubject", "Stay-in-Touch Email Subject", "string", "xsd:string", 80, false, true, false, false, false, false, false);
        fields1.add(sObjectField25);
        final SObjectField sObjectField26 = createField("StayInTouchSignature", "Stay-in-Touch Email Signature", "textarea", "xsd:string", 512, false, true, false, false, false, false, false);
        fields1.add(sObjectField26);
        final SObjectField sObjectField27 = createField("StayInTouchNote", "Stay-in-Touch Email Note", "string", "xsd:string", 512, false, true, false, false, false, false, false);
        fields1.add(sObjectField27);
        final SObjectField sObjectField28 = createField("Phone", "Phone", "phone", "xsd:string", 40, false, true, false, false, false, false, false);
        fields1.add(sObjectField28);
        final SObjectField sObjectField29 = createField("Fax", "Fax", "phone", "xsd:string", 40, false, true, false, false, false, false, false);
        fields1.add(sObjectField29);
        final SObjectField sObjectField30 = createField("MobilePhone", "Mobile", "phone", "xsd:string", 40, false, true, false, false, false, false, false);
        fields1.add(sObjectField30);
        final SObjectField sObjectField31 = createField("Alias", "Alias", "string", "xsd:string", 8, false, false, false, false, false, false, false);
        fields1.add(sObjectField31);
        final SObjectField sObjectField32 = createField("CommunityNickname", "Nickname", "string", "xsd:string", 40, false, false, false, false, false, false, false);
        fields1.add(sObjectField32);
        final SObjectField sObjectField33 = createField("BadgeText", "User Photo badge text overlay", "string", "xsd:string", 80, false, true, false, false, false, false, false);
        fields1.add(sObjectField33);
        final SObjectField sObjectField34 = createField("IsActive", "Active", "boolean", "xsd:boolean", 0, false, false, false, false, false, false, false);
        fields1.add(sObjectField34);
        final SObjectField sObjectField35 = createField("TimeZoneSidKey", "Time Zone", "picklist", "xsd:string", 40, false, false, false, false, false, false, false);
        fields1.add(sObjectField35);
        final SObjectField sObjectField36 = createField("UserRoleId", "Role ID", "reference", "tns:ID", 18, false, true, false, false, false, false, false);
        fields1.add(sObjectField36);
        final SObjectField sObjectField37 = createField("LocaleSidKey", "Locale", "picklist", "xsd:string", 40, false, false, false, false, false, false, false);
        fields1.add(sObjectField37);
        final SObjectField sObjectField38 = createField("ReceivesInfoEmails", "Info Emails", "boolean", "xsd:boolean", 0, false, false, false, false, false, false, false);
        fields1.add(sObjectField38);
        final SObjectField sObjectField39 = createField("ReceivesAdminInfoEmails", "Admin Info Emails", "boolean", "xsd:boolean", 0, false, false, false, false, false, false, false);
        fields1.add(sObjectField39);
        final SObjectField sObjectField40 = createField("EmailEncodingKey", "Email Encoding", "picklist", "xsd:string", 40, false, false, false, false, false, false, false);
        fields1.add(sObjectField40);
        final SObjectField sObjectField41 = createField("ProfileId", "Profile ID", "reference", "tns:ID", 18, false, false, false, false, false, false, false);
        fields1.add(sObjectField41);
        final SObjectField sObjectField42 = createField("UserType", "User Type", "picklist", "xsd:string", 40, false, true, false, false, false, false, false);
        fields1.add(sObjectField42);
        final SObjectField sObjectField43 = createField("LanguageLocaleKey", "Language", "picklist", "xsd:string", 40, false, false, false, false, false, false, false);
        fields1.add(sObjectField43);
        final SObjectField sObjectField44 = createField("EmployeeNumber", "Employee Number", "string", "xsd:string", 20, false, true, false, false, false, false, false);
        fields1.add(sObjectField44);
        final SObjectField sObjectField45 = createField("DelegatedApproverId", "Delegated Approver ID", "reference", "tns:ID", 18, false, true, false, false, false, false, false);
        fields1.add(sObjectField45);
        final SObjectField sObjectField46 = createField("ManagerId", "Manager ID", "reference", "tns:ID", 18, false, true, false, false, false, false, false);
        fields1.add(sObjectField46);
        final SObjectField sObjectField47 = createField("LastLoginDate", "Last Login", "datetime", "xsd:dateTime", 0, false, true, false, false, false, false, false);
        fields1.add(sObjectField47);
        final SObjectField sObjectField48 = createField("LastPasswordChangeDate", "Last Password Change or Reset", "datetime", "xsd:dateTime", 0, false, true, false, false, false, false, false);
        fields1.add(sObjectField48);
        final SObjectField sObjectField49 = createField("CreatedDate", "Created Date", "datetime", "xsd:dateTime", 0, false, false, false, false, false, false, false);
        fields1.add(sObjectField49);
        final SObjectField sObjectField50 = createField("CreatedById", "Created By ID", "reference", "tns:ID", 18, false, false, false, false, false, false, false);
        fields1.add(sObjectField50);
        final SObjectField sObjectField51 = createField("LastModifiedDate", "Last Modified Date", "datetime", "xsd:dateTime", 0, false, false, false, false, false, false, false);
        fields1.add(sObjectField51);
        final SObjectField sObjectField52 = createField("LastModifiedById", "Last Modified By ID", "reference", "tns:ID", 18, false, false, false, false, false, false, false);
        fields1.add(sObjectField52);
        final SObjectField sObjectField53 = createField("SystemModstamp", "System Modstamp", "datetime", "xsd:dateTime", 0, false, false, false, false, false, false, false);
        fields1.add(sObjectField53);
        final SObjectField sObjectField54 = createField("OfflineTrialExpirationDate", "Offline Edition Trial Expiration Date", "datetime", "xsd:dateTime", 0, false, true, false, false, false, false, false);
        fields1.add(sObjectField54);
        final SObjectField sObjectField55 = createField("OfflinePdaTrialExpirationDate", "Sales Anywhere Trial Expiration Date", "datetime", "xsd:dateTime", 0, false, true, false, false, false, false, false);
        fields1.add(sObjectField55);
        final SObjectField sObjectField56 = createField("UserPermissionsMarketingUser", "Marketing User", "boolean", "xsd:boolean", 0, false, false, false, false, false, false, false);
        fields1.add(sObjectField56);
        final SObjectField sObjectField57 = createField("UserPermissionsOfflineUser", "Offline User", "boolean", "xsd:boolean", 0, false, false, false, false, false, false, false);
        fields1.add(sObjectField57);
        final SObjectField sObjectField58 = createField("UserPermissionsCallCenterAutoLogin", "Auto-login To Call Center", "boolean", "xsd:boolean", 0, false, false, false, false, false, false, false);
        fields1.add(sObjectField58);
        final SObjectField sObjectField59 = createField("UserPermissionsMobileUser", "Apex Mobile User", "boolean", "xsd:boolean", 0, false, false, false, false, false, false, false);
        fields1.add(sObjectField59);
        final SObjectField sObjectField60 = createField("UserPermissionsSFContentUser", "Salesforce CRM Content User", "boolean", "xsd:boolean", 0, false, false, false, false, false, false, false);
        fields1.add(sObjectField60);
        final SObjectField sObjectField61 = createField("UserPermissionsKnowledgeUser", "Knowledge User", "boolean", "xsd:boolean", 0, false, false, false, false, false, false, false);
        fields1.add(sObjectField61);
        final SObjectField sObjectField62 = createField("UserPermissionsInteractionUser", "Flow User", "boolean", "xsd:boolean", 0, false, false, false, false, false, false, false);
        fields1.add(sObjectField62);
        final SObjectField sObjectField63 = createField("UserPermissionsSupportUser", "Service Cloud User", "boolean", "xsd:boolean", 0, false, false, false, false, false, false, false);
        fields1.add(sObjectField63);
        final SObjectField sObjectField64 = createField("UserPermissionsJigsawProspectingUser", "Data.com User", "boolean", "xsd:boolean", 0, false, false, false, false, false, false, false);
        fields1.add(sObjectField64);
        final SObjectField sObjectField65 = createField("UserPermissionsSiteforceContributorUser", "Site.com Contributor User", "boolean", "xsd:boolean", 0, false, false, false, false, false, false, false);
        fields1.add(sObjectField65);
        final SObjectField sObjectField66 = createField("UserPermissionsSiteforcePublisherUser", "Site.com Publisher User", "boolean", "xsd:boolean", 0, false, false, false, false, false, false, false);
        fields1.add(sObjectField66);
        final SObjectField sObjectField67 = createField("UserPermissionsWorkDotComUserFeature", "Work.com User", "boolean", "xsd:boolean", 0, false, false, false, false, false, false, false);
        fields1.add(sObjectField67);
        final SObjectField sObjectField68 = createField("ForecastEnabled", "Allow Forecasting", "boolean", "xsd:boolean", 0, false, false, false, false, false, false, false);
        fields1.add(sObjectField68);
        final SObjectField sObjectField69 = createField("UserPreferencesActivityRemindersPopup", "ActivityRemindersPopup", "boolean", "xsd:boolean", 0, false, false, false, false, false, false, false);
        fields1.add(sObjectField69);
        final SObjectField sObjectField70 = createField("UserPreferencesEventRemindersCheckboxDefault", "EventRemindersCheckboxDefault", "boolean", "xsd:boolean", 0, false, false, false, false, false, false, false);
        fields1.add(sObjectField70);
        final SObjectField sObjectField71 = createField("UserPreferencesTaskRemindersCheckboxDefault", "TaskRemindersCheckboxDefault", "boolean", "xsd:boolean", 0, false, false, false, false, false, false, false);
        fields1.add(sObjectField71);
        final SObjectField sObjectField72 = createField("UserPreferencesReminderSoundOff", "ReminderSoundOff", "boolean", "xsd:boolean", 0, false, false, false, false, false, false, false);
        fields1.add(sObjectField72);
        final SObjectField sObjectField73 = createField("UserPreferencesDisableAllFeedsEmail", "DisableAllFeedsEmail", "boolean", "xsd:boolean", 0, false, false, false, false, false, false, false);
        fields1.add(sObjectField73);
        final SObjectField sObjectField74 = createField("UserPreferencesDisableFollowersEmail", "DisableFollowersEmail", "boolean", "xsd:boolean", 0, false, false, false, false, false, false, false);
        fields1.add(sObjectField74);
        final SObjectField sObjectField75 = createField("UserPreferencesDisableProfilePostEmail", "DisableProfilePostEmail", "boolean", "xsd:boolean", 0, false, false, false, false, false, false, false);
        fields1.add(sObjectField75);
        final SObjectField sObjectField76 = createField("UserPreferencesDisableChangeCommentEmail", "DisableChangeCommentEmail", "boolean", "xsd:boolean", 0, false, false, false, false, false, false, false);
        fields1.add(sObjectField76);
        final SObjectField sObjectField77 = createField("UserPreferencesDisableLaterCommentEmail", "DisableLaterCommentEmail", "boolean", "xsd:boolean", 0, false, false, false, false, false, false, false);
        fields1.add(sObjectField77);
        final SObjectField sObjectField78 = createField("UserPreferencesDisProfPostCommentEmail", "DisProfPostCommentEmail", "boolean", "xsd:boolean", 0, false, false, false, false, false, false, false);
        fields1.add(sObjectField78);
        final SObjectField sObjectField79 = createField("UserPreferencesContentNoEmail", "ContentNoEmail", "boolean", "xsd:boolean", 0, false, false, false, false, false, false, false);
        fields1.add(sObjectField79);
        final SObjectField sObjectField80 = createField("UserPreferencesContentEmailAsAndWhen", "ContentEmailAsAndWhen", "boolean", "xsd:boolean", 0, false, false, false, false, false, false, false);
        fields1.add(sObjectField80);
        final SObjectField sObjectField81 = createField("UserPreferencesApexPagesDeveloperMode", "ApexPagesDeveloperMode", "boolean", "xsd:boolean", 0, false, false, false, false, false, false, false);
        fields1.add(sObjectField81);
        final SObjectField sObjectField82 = createField("UserPreferencesHideCSNGetChatterMobileTask", "HideCSNGetChatterMobileTask", "boolean", "xsd:boolean", 0, false, false, false, false, false, false, false);
        fields1.add(sObjectField82);
        final SObjectField sObjectField83 = createField("UserPreferencesDisableMentionsPostEmail", "DisableMentionsPostEmail", "boolean", "xsd:boolean", 0, false, false, false, false, false, false, false);
        fields1.add(sObjectField83);
        final SObjectField sObjectField84 = createField("UserPreferencesDisMentionsCommentEmail", "DisMentionsCommentEmail", "boolean", "xsd:boolean", 0, false, false, false, false, false, false, false);
        fields1.add(sObjectField84);
        final SObjectField sObjectField85 = createField("UserPreferencesHideCSNDesktopTask", "HideCSNDesktopTask", "boolean", "xsd:boolean", 0, false, false, false, false, false, false, false);
        fields1.add(sObjectField85);
        final SObjectField sObjectField86 = createField("UserPreferencesHideChatterOnboardingSplash", "HideChatterOnboardingSplash", "boolean", "xsd:boolean", 0, false, false, false, false, false, false, false);
        fields1.add(sObjectField86);
        final SObjectField sObjectField87 = createField("UserPreferencesHideSecondChatterOnboardingSplash", "HideSecondChatterOnboardingSplash", "boolean", "xsd:boolean", 0, false, false, false, false, false, false, false);
        fields1.add(sObjectField87);
        final SObjectField sObjectField88 = createField("UserPreferencesDisCommentAfterLikeEmail", "DisCommentAfterLikeEmail", "boolean", "xsd:boolean", 0, false, false, false, false, false, false, false);
        fields1.add(sObjectField88);
        final SObjectField sObjectField89 = createField("UserPreferencesDisableLikeEmail", "DisableLikeEmail", "boolean", "xsd:boolean", 0, false, false, false, false, false, false, false);
        fields1.add(sObjectField89);
        final SObjectField sObjectField90 = createField("UserPreferencesSortFeedByComment", "SortFeedByComment", "boolean", "xsd:boolean", 0, false, false, false, false, false, false, false);
        fields1.add(sObjectField90);
        final SObjectField sObjectField91 = createField("UserPreferencesDisableMessageEmail", "DisableMessageEmail", "boolean", "xsd:boolean", 0, false, false, false, false, false, false, false);
        fields1.add(sObjectField91);
        final SObjectField sObjectField92 = createField("UserPreferencesJigsawListUser", "JigsawListUser", "boolean", "xsd:boolean", 0, false, false, false, false, false, false, false);
        fields1.add(sObjectField92);
        final SObjectField sObjectField93 = createField("UserPreferencesDisableBookmarkEmail", "DisableBookmarkEmail", "boolean", "xsd:boolean", 0, false, false, false, false, false, false, false);
        fields1.add(sObjectField93);
        final SObjectField sObjectField94 = createField("UserPreferencesDisableSharePostEmail", "DisableSharePostEmail", "boolean", "xsd:boolean", 0, false, false, false, false, false, false, false);
        fields1.add(sObjectField94);
        final SObjectField sObjectField95 = createField("UserPreferencesEnableAutoSubForFeeds", "EnableAutoSubForFeeds", "boolean", "xsd:boolean", 0, false, false, false, false, false, false, false);
        fields1.add(sObjectField95);
        final SObjectField sObjectField96 = createField("UserPreferencesDisableFileShareNotificationsForApi", "DisableFileShareNotificationsForApi", "boolean", "xsd:boolean", 0, false, false, false, false, false, false, false);
        fields1.add(sObjectField96);
        final SObjectField sObjectField97 = createField("UserPreferencesShowTitleToExternalUsers", "ShowTitleToExternalUsers", "boolean", "xsd:boolean", 0, false, false, false, false, false, false, false);
        fields1.add(sObjectField97);
        final SObjectField sObjectField98 = createField("UserPreferencesShowManagerToExternalUsers", "ShowManagerToExternalUsers", "boolean", "xsd:boolean", 0, false, false, false, false, false, false, false);
        fields1.add(sObjectField98);
        final SObjectField sObjectField99 = createField("UserPreferencesShowEmailToExternalUsers", "ShowEmailToExternalUsers", "boolean", "xsd:boolean", 0, false, false, false, false, false, false, false);
        fields1.add(sObjectField99);
        final SObjectField sObjectField100 = createField("UserPreferencesShowWorkPhoneToExternalUsers", "ShowWorkPhoneToExternalUsers", "boolean", "xsd:boolean", 0, false, false, false, false, false, false, false);
        fields1.add(sObjectField100);
        final SObjectField sObjectField101 = createField("UserPreferencesShowMobilePhoneToExternalUsers", "ShowMobilePhoneToExternalUsers", "boolean", "xsd:boolean", 0, false, false, false, false, false, false, false);
        fields1.add(sObjectField101);
        final SObjectField sObjectField102 = createField("UserPreferencesShowFaxToExternalUsers", "ShowFaxToExternalUsers", "boolean", "xsd:boolean", 0, false, false, false, false, false, false, false);
        fields1.add(sObjectField102);
        final SObjectField sObjectField103 = createField("UserPreferencesShowStreetAddressToExternalUsers", "ShowStreetAddressToExternalUsers", "boolean", "xsd:boolean", 0, false, false, false, false, false, false, false);
        fields1.add(sObjectField103);
        final SObjectField sObjectField104 = createField("UserPreferencesShowCityToExternalUsers", "ShowCityToExternalUsers", "boolean", "xsd:boolean", 0, false, false, false, false, false, false, false);
        fields1.add(sObjectField104);
        final SObjectField sObjectField105 = createField("UserPreferencesShowStateToExternalUsers", "ShowStateToExternalUsers", "boolean", "xsd:boolean", 0, false, false, false, false, false, false, false);
        fields1.add(sObjectField105);
        final SObjectField sObjectField106 = createField("UserPreferencesShowPostalCodeToExternalUsers", "ShowPostalCodeToExternalUsers", "boolean", "xsd:boolean", 0, false, false, false, false, false, false, false);
        fields1.add(sObjectField106);
        final SObjectField sObjectField107 = createField("UserPreferencesShowCountryToExternalUsers", "ShowCountryToExternalUsers", "boolean", "xsd:boolean", 0, false, false, false, false, false, false, false);
        fields1.add(sObjectField107);
        final SObjectField sObjectField108 = createField("UserPreferencesShowProfilePicToGuestUsers", "ShowProfilePicToGuestUsers", "boolean", "xsd:boolean", 0, false, false, false, false, false, false, false);
        fields1.add(sObjectField108);
        final SObjectField sObjectField109 = createField("UserPreferencesShowTitleToGuestUsers", "ShowTitleToGuestUsers", "boolean", "xsd:boolean", 0, false, false, false, false, false, false, false);
        fields1.add(sObjectField109);
        final SObjectField sObjectField110 = createField("UserPreferencesShowCityToGuestUsers", "ShowCityToGuestUsers", "boolean", "xsd:boolean", 0, false, false, false, false, false, false, false);
        fields1.add(sObjectField110);
        final SObjectField sObjectField111 = createField("UserPreferencesShowStateToGuestUsers", "ShowStateToGuestUsers", "boolean", "xsd:boolean", 0, false, false, false, false, false, false, false);
        fields1.add(sObjectField111);
        final SObjectField sObjectField112 = createField("UserPreferencesShowPostalCodeToGuestUsers", "ShowPostalCodeToGuestUsers", "boolean", "xsd:boolean", 0, false, false, false, false, false, false, false);
        fields1.add(sObjectField112);
        final SObjectField sObjectField113 = createField("UserPreferencesShowCountryToGuestUsers", "ShowCountryToGuestUsers", "boolean", "xsd:boolean", 0, false, false, false, false, false, false, false);
        fields1.add(sObjectField113);
        final SObjectField sObjectField114 = createField("UserPreferencesDisableFeedbackEmail", "DisableFeedbackEmail", "boolean", "xsd:boolean", 0, false, false, false, false, false, false, false);
        fields1.add(sObjectField114);
        final SObjectField sObjectField115 = createField("UserPreferencesDisableWorkEmail", "DisableWorkEmail", "boolean", "xsd:boolean", 0, false, false, false, false, false, false, false);
        fields1.add(sObjectField115);
        final SObjectField sObjectField116 = createField("UserPreferencesHideS1BrowserUI", "HideS1BrowserUI", "boolean", "xsd:boolean", 0, false, false, false, false, false, false, false);
        fields1.add(sObjectField116);
        final SObjectField sObjectField117 = createField("UserPreferencesDisableEndorsementEmail", "DisableEndorsementEmail", "boolean", "xsd:boolean", 0, false, false, false, false, false, false, false);
        fields1.add(sObjectField117);
        final SObjectField sObjectField118 = createField("UserPreferencesPathAssistantCollapsed", "PathAssistantCollapsed", "boolean", "xsd:boolean", 0, false, false, false, false, false, false, false);
        fields1.add(sObjectField118);
        final SObjectField sObjectField119 = createField("UserPreferencesCacheDiagnostics", "CacheDiagnostics", "boolean", "xsd:boolean", 0, false, false, false, false, false, false, false);
        fields1.add(sObjectField119);
        final SObjectField sObjectField120 = createField("UserPreferencesShowEmailToGuestUsers", "ShowEmailToGuestUsers", "boolean", "xsd:boolean", 0, false, false, false, false, false, false, false);
        fields1.add(sObjectField120);
        final SObjectField sObjectField121 = createField("UserPreferencesShowManagerToGuestUsers", "ShowManagerToGuestUsers", "boolean", "xsd:boolean", 0, false, false, false, false, false, false, false);
        fields1.add(sObjectField121);
        final SObjectField sObjectField122 = createField("UserPreferencesShowWorkPhoneToGuestUsers", "ShowWorkPhoneToGuestUsers", "boolean", "xsd:boolean", 0, false, false, false, false, false, false, false);
        fields1.add(sObjectField122);
        final SObjectField sObjectField123 = createField("UserPreferencesShowMobilePhoneToGuestUsers", "ShowMobilePhoneToGuestUsers", "boolean", "xsd:boolean", 0, false, false, false, false, false, false, false);
        fields1.add(sObjectField123);
        final SObjectField sObjectField124 = createField("UserPreferencesShowFaxToGuestUsers", "ShowFaxToGuestUsers", "boolean", "xsd:boolean", 0, false, false, false, false, false, false, false);
        fields1.add(sObjectField124);
        final SObjectField sObjectField125 = createField("UserPreferencesShowStreetAddressToGuestUsers", "ShowStreetAddressToGuestUsers", "boolean", "xsd:boolean", 0, false, false, false, false, false, false, false);
        fields1.add(sObjectField125);
        final SObjectField sObjectField126 = createField("UserPreferencesLightningExperiencePreferred", "LightningExperiencePreferred", "boolean", "xsd:boolean", 0, false, false, false, false, false, false, false);
        fields1.add(sObjectField126);
        final SObjectField sObjectField127 = createField("ContactId", "Contact ID", "reference", "tns:ID", 18, false, true, false, false, false, false, false);
        fields1.add(sObjectField127);
        final SObjectField sObjectField128 = createField("AccountId", "Account ID", "reference", "tns:ID", 18, false, true, false, false, false, false, false);
        fields1.add(sObjectField128);
        final SObjectField sObjectField129 = createField("CallCenterId", "Call Center ID", "reference", "tns:ID", 18, false, true, false, false, false, false, false);
        fields1.add(sObjectField129);
        final SObjectField sObjectField130 = createField("Extension", "Extension", "phone", "xsd:string", 40, false, true, false, false, false, false, false);
        fields1.add(sObjectField130);
        final SObjectField sObjectField131 = createField("FederationIdentifier", "SAML Federation ID", "string", "xsd:string", 512, false, true, false, false, false, false, true);
        fields1.add(sObjectField131);
        final SObjectField sObjectField132 = createField("AboutMe", "About Me", "textarea", "xsd:string", 1000, false, true, false, false, false, false, false);
        fields1.add(sObjectField132);
        final SObjectField sObjectField133 = createField("FullPhotoUrl", "Url for full-sized Photo", "url", "xsd:string", 1024, false, true, false, false, false, false, false);
        fields1.add(sObjectField133);
        final SObjectField sObjectField134 = createField("SmallPhotoUrl", "Photo", "url", "xsd:string", 1024, false, true, false, false, false, false, false);
        fields1.add(sObjectField134);
        final SObjectField sObjectField135 = createField("DigestFrequency", "Chatter Email Highlights Frequency", "picklist", "xsd:string", 40, false, false, false, false, false, false, false);
        fields1.add(sObjectField135);
        final SObjectField sObjectField136 = createField("DefaultGroupNotificationFrequency", "Default Notification Frequency when Joining Groups", "picklist", "xsd:string", 40, false, false, false, false, false, false, false);
        fields1.add(sObjectField136);
        final SObjectField sObjectField137 = createField("JigsawImportLimitOverride", "Data.com Monthly Addition Limit", "int", "xsd:int", 0, false, true, false, false, false, false, false);
        fields1.add(sObjectField137);
        final SObjectField sObjectField138 = createField("LastViewedDate", "Last Viewed Date", "datetime", "xsd:dateTime", 0, false, true, false, false, false, false, false);
        fields1.add(sObjectField138);
        final SObjectField sObjectField139 = createField("LastReferencedDate", "Last Referenced Date", "datetime", "xsd:dateTime", 0, false, true, false, false, false, false, false);
        fields1.add(sObjectField139);

        description.setLabel("User");
        description.setLabelPlural("Users");
        description.setName("User");

        final SObjectDescriptionUrls sObjectDescriptionUrls1 = new SObjectDescriptionUrls();
        sObjectDescriptionUrls1.setCompactLayouts("/services/data/v34.0/sobjects/User/describe/compactLayouts");
        sObjectDescriptionUrls1.setDescribe("/services/data/v34.0/sobjects/User/describe");
        sObjectDescriptionUrls1.setLayouts("/services/data/v34.0/sobjects/User/describe/layouts");
        sObjectDescriptionUrls1.setNamedLayouts("/services/data/v34.0/sobjects/User/describe/namedLayouts/{LayoutName}");
        sObjectDescriptionUrls1.setPasswordUtilities("/services/data/v34.0/sobjects/User/{ID}/password");
        sObjectDescriptionUrls1.setQuickActions("/services/data/v34.0/sobjects/User/quickActions");
        sObjectDescriptionUrls1.setRowTemplate("/services/data/v34.0/sobjects/User/{ID}");
        sObjectDescriptionUrls1.setSobject("/services/data/v34.0/sobjects/User");
        sObjectDescriptionUrls1.setUiDetailTemplate("https://eu13.salesforce.com/{ID}");
        sObjectDescriptionUrls1.setUiEditTemplate("https://eu13.salesforce.com/{ID}/e");
        sObjectDescriptionUrls1.setUiNewRecord("https://eu13.salesforce.com/005/e");
        description.setUrls(sObjectDescriptionUrls1);

        return description;
    }
}
