/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 */
package org.wildfly.camel.test.salesforce.dto;

import javax.annotation.Generated;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Salesforce Enumeration DTO for picklist LocaleSidKey
 */
@Generated("org.apache.camel.maven.CamelSalesforceMojo")
public enum User_LocaleSidKeyEnum {

    // ar_AE
    AR_AE("ar_AE"),

    // ar_BH
    AR_BH("ar_BH"),

    // ar_DZ
    AR_DZ("ar_DZ"),

    // ar_EG
    AR_EG("ar_EG"),

    // ar_IQ
    AR_IQ("ar_IQ"),

    // ar_JO
    AR_JO("ar_JO"),

    // ar_KW
    AR_KW("ar_KW"),

    // ar_LB
    AR_LB("ar_LB"),

    // ar_LY
    AR_LY("ar_LY"),

    // ar_MA
    AR_MA("ar_MA"),

    // ar_OM
    AR_OM("ar_OM"),

    // ar_QA
    AR_QA("ar_QA"),

    // ar_SA
    AR_SA("ar_SA"),

    // ar_SD
    AR_SD("ar_SD"),

    // ar_SY
    AR_SY("ar_SY"),

    // ar_TN
    AR_TN("ar_TN"),

    // ar_YE
    AR_YE("ar_YE"),

    // az_AZ
    AZ_AZ("az_AZ"),

    // be_BY
    BE_BY("be_BY"),

    // bg_BG
    BG_BG("bg_BG"),

    // bn_BD
    BN_BD("bn_BD"),

    // bs_BA
    BS_BA("bs_BA"),

    // ca_ES
    CA_ES("ca_ES"),

    // cs_CZ
    CS_CZ("cs_CZ"),

    // cy_GB
    CY_GB("cy_GB"),

    // da_DK
    DA_DK("da_DK"),

    // de_AT
    DE_AT("de_AT"),

    // de_CH
    DE_CH("de_CH"),

    // de_DE
    DE_DE("de_DE"),

    // de_LU
    DE_LU("de_LU"),

    // dz_BT
    DZ_BT("dz_BT"),

    // el_GR
    EL_GR("el_GR"),

    // en_AG
    EN_AG("en_AG"),

    // en_AU
    EN_AU("en_AU"),

    // en_BB
    EN_BB("en_BB"),

    // en_BM
    EN_BM("en_BM"),

    // en_BS
    EN_BS("en_BS"),

    // en_BW
    EN_BW("en_BW"),

    // en_BZ
    EN_BZ("en_BZ"),

    // en_CA
    EN_CA("en_CA"),

    // en_CM
    EN_CM("en_CM"),

    // en_ER
    EN_ER("en_ER"),

    // en_FJ
    EN_FJ("en_FJ"),

    // en_FK
    EN_FK("en_FK"),

    // en_GB
    EN_GB("en_GB"),

    // en_GH
    EN_GH("en_GH"),

    // en_GI
    EN_GI("en_GI"),

    // en_GM
    EN_GM("en_GM"),

    // en_GY
    EN_GY("en_GY"),

    // en_HK
    EN_HK("en_HK"),

    // en_ID
    EN_ID("en_ID"),

    // en_IE
    EN_IE("en_IE"),

    // en_IN
    EN_IN("en_IN"),

    // en_JM
    EN_JM("en_JM"),

    // en_KE
    EN_KE("en_KE"),

    // en_KY
    EN_KY("en_KY"),

    // en_LR
    EN_LR("en_LR"),

    // en_MG
    EN_MG("en_MG"),

    // en_MU
    EN_MU("en_MU"),

    // en_MW
    EN_MW("en_MW"),

    // en_MY
    EN_MY("en_MY"),

    // en_NA
    EN_NA("en_NA"),

    // en_NG
    EN_NG("en_NG"),

    // en_NZ
    EN_NZ("en_NZ"),

    // en_PG
    EN_PG("en_PG"),

    // en_PH
    EN_PH("en_PH"),

    // en_PK
    EN_PK("en_PK"),

    // en_RW
    EN_RW("en_RW"),

    // en_SB
    EN_SB("en_SB"),

    // en_SC
    EN_SC("en_SC"),

    // en_SG
    EN_SG("en_SG"),

    // en_SH
    EN_SH("en_SH"),

    // en_SL
    EN_SL("en_SL"),

    // en_SX
    EN_SX("en_SX"),

    // en_SZ
    EN_SZ("en_SZ"),

    // en_TO
    EN_TO("en_TO"),

    // en_TT
    EN_TT("en_TT"),

    // en_TZ
    EN_TZ("en_TZ"),

    // en_UG
    EN_UG("en_UG"),

    // en_US
    EN_US("en_US"),

    // en_VU
    EN_VU("en_VU"),

    // en_WS
    EN_WS("en_WS"),

    // en_ZA
    EN_ZA("en_ZA"),

    // es_AR
    ES_AR("es_AR"),

    // es_BO
    ES_BO("es_BO"),

    // es_CL
    ES_CL("es_CL"),

    // es_CO
    ES_CO("es_CO"),

    // es_CR
    ES_CR("es_CR"),

    // es_CU
    ES_CU("es_CU"),

    // es_DO
    ES_DO("es_DO"),

    // es_EC
    ES_EC("es_EC"),

    // es_ES
    ES_ES("es_ES"),

    // es_GT
    ES_GT("es_GT"),

    // es_HN
    ES_HN("es_HN"),

    // es_MX
    ES_MX("es_MX"),

    // es_NI
    ES_NI("es_NI"),

    // es_PA
    ES_PA("es_PA"),

    // es_PE
    ES_PE("es_PE"),

    // es_PR
    ES_PR("es_PR"),

    // es_PY
    ES_PY("es_PY"),

    // es_SV
    ES_SV("es_SV"),

    // es_US
    ES_US("es_US"),

    // es_UY
    ES_UY("es_UY"),

    // es_VE
    ES_VE("es_VE"),

    // et_EE
    ET_EE("et_EE"),

    // eu_ES
    EU_ES("eu_ES"),

    // fa_IR
    FA_IR("fa_IR"),

    // fi_FI
    FI_FI("fi_FI"),

    // fr_BE
    FR_BE("fr_BE"),

    // fr_CA
    FR_CA("fr_CA"),

    // fr_CH
    FR_CH("fr_CH"),

    // fr_FR
    FR_FR("fr_FR"),

    // fr_GN
    FR_GN("fr_GN"),

    // fr_HT
    FR_HT("fr_HT"),

    // fr_KM
    FR_KM("fr_KM"),

    // fr_LU
    FR_LU("fr_LU"),

    // fr_MC
    FR_MC("fr_MC"),

    // fr_MR
    FR_MR("fr_MR"),

    // fr_WF
    FR_WF("fr_WF"),

    // ga_IE
    GA_IE("ga_IE"),

    // hi_IN
    HI_IN("hi_IN"),

    // hr_HR
    HR_HR("hr_HR"),

    // hu_HU
    HU_HU("hu_HU"),

    // hy_AM
    HY_AM("hy_AM"),

    // in_ID
    IN_ID("in_ID"),

    // is_IS
    IS_IS("is_IS"),

    // it_CH
    IT_CH("it_CH"),

    // it_IT
    IT_IT("it_IT"),

    // iw_IL
    IW_IL("iw_IL"),

    // ja_JP
    JA_JP("ja_JP"),

    // ka_GE
    KA_GE("ka_GE"),

    // kk_KZ
    KK_KZ("kk_KZ"),

    // km_KH
    KM_KH("km_KH"),

    // ko_KP
    KO_KP("ko_KP"),

    // ko_KR
    KO_KR("ko_KR"),

    // ky_KG
    KY_KG("ky_KG"),

    // lb_LU
    LB_LU("lb_LU"),

    // lo_LA
    LO_LA("lo_LA"),

    // lt_LT
    LT_LT("lt_LT"),

    // lu_CD
    LU_CD("lu_CD"),

    // lv_LV
    LV_LV("lv_LV"),

    // mk_MK
    MK_MK("mk_MK"),

    // ms_BN
    MS_BN("ms_BN"),

    // ms_MY
    MS_MY("ms_MY"),

    // mt_MT
    MT_MT("mt_MT"),

    // my_MM
    MY_MM("my_MM"),

    // ne_NP
    NE_NP("ne_NP"),

    // nl_AW
    NL_AW("nl_AW"),

    // nl_BE
    NL_BE("nl_BE"),

    // nl_NL
    NL_NL("nl_NL"),

    // nl_SR
    NL_SR("nl_SR"),

    // no_NO
    NO_NO("no_NO"),

    // pl_PL
    PL_PL("pl_PL"),

    // ps_AF
    PS_AF("ps_AF"),

    // pt_AO
    PT_AO("pt_AO"),

    // pt_BR
    PT_BR("pt_BR"),

    // pt_CV
    PT_CV("pt_CV"),

    // pt_MZ
    PT_MZ("pt_MZ"),

    // pt_PT
    PT_PT("pt_PT"),

    // pt_ST
    PT_ST("pt_ST"),

    // rm_CH
    RM_CH("rm_CH"),

    // rn_BI
    RN_BI("rn_BI"),

    // ro_MD
    RO_MD("ro_MD"),

    // ro_RO
    RO_RO("ro_RO"),

    // ru_RU
    RU_RU("ru_RU"),

    // sh_BA
    SH_BA("sh_BA"),

    // sh_CS
    SH_CS("sh_CS"),

    // sh_ME
    SH_ME("sh_ME"),

    // sk_SK
    SK_SK("sk_SK"),

    // sl_SI
    SL_SI("sl_SI"),

    // so_DJ
    SO_DJ("so_DJ"),

    // so_SO
    SO_SO("so_SO"),

    // sq_AL
    SQ_AL("sq_AL"),

    // sr_BA
    SR_BA("sr_BA"),

    // sr_CS
    SR_CS("sr_CS"),

    // sr_RS
    SR_RS("sr_RS"),

    // sv_SE
    SV_SE("sv_SE"),

    // ta_IN
    TA_IN("ta_IN"),

    // ta_LK
    TA_LK("ta_LK"),

    // tg_TJ
    TG_TJ("tg_TJ"),

    // th_TH
    TH_TH("th_TH"),

    // ti_ET
    TI_ET("ti_ET"),

    // tl_PH
    TL_PH("tl_PH"),

    // tr_TR
    TR_TR("tr_TR"),

    // uk_UA
    UK_UA("uk_UA"),

    // ur_PK
    UR_PK("ur_PK"),

    // uz_LATN_UZ
    UZ_LATN_UZ("uz_LATN_UZ"),

    // vi_VN
    VI_VN("vi_VN"),

    // yo_BJ
    YO_BJ("yo_BJ"),

    // zh_CN
    ZH_CN("zh_CN"),

    // zh_CN_PINYIN
    ZH_CN_PINYIN("zh_CN_PINYIN"),

    // zh_CN_STROKE
    ZH_CN_STROKE("zh_CN_STROKE"),

    // zh_HK
    ZH_HK("zh_HK"),

    // zh_HK_STROKE
    ZH_HK_STROKE("zh_HK_STROKE"),

    // zh_MO
    ZH_MO("zh_MO"),

    // zh_SG
    ZH_SG("zh_SG"),

    // zh_TW
    ZH_TW("zh_TW"),

    // zh_TW_STROKE
    ZH_TW_STROKE("zh_TW_STROKE");


    final String value;

    private User_LocaleSidKeyEnum(String value) {
        this.value = value;
    }

    @JsonValue
    public String value() {
        return this.value;
    }

    @JsonCreator
    public static User_LocaleSidKeyEnum fromValue(String value) {
        for (User_LocaleSidKeyEnum e : User_LocaleSidKeyEnum.values()) {
            if (e.value.equals(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException(value);
    }

}
