#
# The PR processing workflow
#

name: QA Default

# Controls when the action will run. 
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  
  # A job that does the build
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    # Setup Java JDK8
    - uses: actions/setup-java@v1
      with:
        java-version: 1.8
    
    # Cache maven dependencies
    - uses: actions/cache@v2
      with:
        path: ~/.m2
        key: m2local

    #
    # Run the maven build
    #
    
    - name: Run the maven build
      run: mvn -B clean install -Dts.all

    #
    # Run post maven build steps on FAILURE
    #
    
    - name: Post build on FAILURE
      if: failure()
      run:  |
        mkdir surefire-reports
        cp */surefire-reports/*.txt surefire-reports
        tar czf surefire-reports.tgz surefire-reports
      
    - name: Upload surefire results on FAILURE
      if: failure()
      uses: actions/upload-artifact@v1
      with:
        name: surefire-reports
        path: surefire-reports.tgz
        
